### DISCUSSION TITLE
Do you have a recipe that requires a lot of memory or time to run?

### DISCUSSION THREAD

**Discussion by bouweandela** [ESMValGroup/ESMValCore#1763] [Ideas]
If you have a recipe that requires a lot of memory or takes a long time to run, please share it here. We will use those to test the new and [improved dask support](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html#dask-distributed-configuration). Further performance optimizations are planned in https://github.com/ESMValGroup/ESMValCore/issues/2041 and https://github.com/ESMValGroup/ESMValCore/issues/2042. This works with [lazy](https://scitools-iris.readthedocs.io/en/latest/userguide/real_and_lazy_data.html) (preprocessor) functions, see https://github.com/ESMValGroup/ESMValCore/issues/674 for progress on making preprocessor functions lazy. 

You can just attach your recipe to the answer (rename it to .txt so GitHub allows attaching it) or copy/paste it below.

We're specifically interested in improving the (memory) performance of the preprocessing, so any diagnostic scripts can be left out of the recipe if you're not ready to share those.

@ESMValGroup/esmvaltool-developmentteam

**Comment by pepcos** [comment]
Here is one example, if more come to mind I'll add them.

This one is not super heavy memory-wise but it would be great to have as many processes running at once (which might benefit from computing in multiple nodes as not all machines have the amazing amount of cores per node that Levante has).

[recipe_decadal_parallel_tasks.txt](https://github.com/ESMValGroup/ESMValCore/files/9832511/recipe_decadal_parallel_tasks.txt)

**Reply by bouweandela** [reply]
Thanks, I'll get back to you once we have some results.

**Comment by Peter9192** [comment]
The recipe for wflow forcing is also very memory-heavy. That's mostly the diagnostic script, which *does* use the esmvaltool regridding function. `/hydrology/recipe_wflow.yaml`. If it helps, I could prep a version that moves the regridding to the preprocessor?

**Reply by bouweandela** [reply]
Yes, that would be great!

**Reply by Peter9192** [reply]
There you go. I tried using the lazy regridder from iris-esmf-regrid, not sure if you prefer this or the standard regridder for your optimization exercise. You can easily play with the resolution or the number of years to make it more or less challenging. The current settings reflect our real-world use case.

<details><summary>recipe_wflow_testcase.yml</summary>

```yaml

# ESMValTool
# recipe_wflow_testcase.yml
---
documentation:
  title: Test recipe for performance optimization.
  description: |
    Pre-processes climate data for the WFlow hydrological model.

  authors:
    - kalverla_peter

preprocessors:
  regrid:
    regrid:
      # Ideally we want ~1 km grid spacing with a custom grid definition. This
      # requires a lazy regridder or a huge amount of memory.
      target_grid:
        start_longitude: 5.4
        end_longitude: 11.8
        start_latitude: 46.3
        end_latitude: 51.9
        step_latitude: 0.01
        step_longitude: 0.01
      scheme:
        # Trying to use (experimental) lazy regridder
        reference: esmf_regrid.schemes:ESMFAreaWeighted

diagnostics:
  wflow_daily:
    description: WFlow input preprocessor for daily data
    additional_datasets:
      - {dataset: ERA-Interim, project: OBS6, tier: 3, type: reanaly, version: 1}  # or any other
    variables:
      orog:
        mip: fx
        preprocessor: regrid
      tas: &daily_var
        mip: day
        preprocessor: regrid
        start_year: 2001
        end_year: 2016
      pr: *daily_var
      psl: *daily_var
      rsds: *daily_var
      rsdt:
        <<: *daily_var
        mip: CFday
    scripts: null

```

</details>
