### ISSUE TITLE
Old gripe: throw an exception and kill the run if project in both dataset dictionary and variable (and differs)

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1077]
When working with different projects inside the same diagnostic run, and/or custom variables, one may make the mistake to specify a `project:` key in the `dataset` dictionary(ies) and specify it again in the `variable: var:` section - all hell breaks loose with CMOR table finder and loader not finding tables because the `cmor_strict:` key is set one way whereas the project from var needs a different `cmor_strict`. At the moment we are not catching this and a large recipe with a single extra `project:` in the wrong place can make you look through failed output for a whole afternoon. Can you guys make sure this is taken care of please? :beer: 

Example of case that'll confuse the cmor table finder/loader:
```yaml
datasets:
  - {dataset: CESM2, project: CMIP6, exp: historical, ensemble: r(2:3)i1p1f1, start_year: 2004, end_year: 2005, grid: gn}
  - {dataset: UKESM1-0-LL, project: CMIP6, exp: historical, ensemble: r1i1p1f2, start_year: 2010, end_year: 2010, grid: gn}
  - {dataset: ESACCI_LST_UNCERT, project: OBS, type: sat, tier: 2, start_year: 2010, end_year: 2010, version: '1.00'}
  

diagnostics:

  timeseries:
    description: ESACCI LST difference to model historical ensemble average
    themes:
      - phys
    realms:
      - atmos
    variables:
      tsLocalSfcErr:
        project: OBS
        mip: Amon
        preprocessor: lst_preprocessor
      ts:
        mip: Amon
        project: CMIP6
    scripts:
      script1:
        script: lst_uncert/lst_uncert.py
```
