### ISSUE TITLE
Issues with preprocessors that use fx variables

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1096]
I found some small issues with the new implementation of the fx preprocessors in #999 (great job btw there @sloosvel!).

Issues
---------

1. Not directly related to #999, but do we have a list of all preprocessors for which `fx_variables` can be specified? Maybe I'm blind, but I didn't find it in the documentation. Basically the list given here: https://github.com/ESMValGroup/ESMValCore/blob/fee5d541dc871efe72ab972a6a52195c452d16eb/esmvalcore/_recipe.py#L482-L485

2. For `mask_landsea` we had checks for the shape of the fx variables in place. If the shapes did not match, Natural Earth masks were used. Right now, if the shapes do not match, an error is printed as reported by @LisaBock [here](https://github.com/ESMValGroup/ESMValTool/issues/2155#issuecomment-832060910): `ValueError: Dimensions of tas and sftof cubes do not match. Cannot broadcast cubes.` This is in particular problematic since for `mask_landsea`, the tool automatically adds the fx variables `sftlf` and `sftof` if none is specified. Since `sftlf` is always checked first, the tool is most likely to fail if an ocean variable is specified since the shapes of `sfltf` and ocean variables differ for most models. For example, the first recipe fails with the error `ValueError: Dimensions of tos and sftlf cubes do not match. Cannot broadcast cubes.`, and the second one runs fine:

<details>
  <summary>Recipe 1 (fails)</summary>
  
  ```yml
preprocessors:
  test:
    mask_landsea:
      mask_out: land

diagnostics:

  test:
    variables:
      tos:
        preprocessor: test
        project: CMIP5
        mip: Omon
        exp: historical
        start_year: 2000
        end_year: 2000
        ensemble: r1i1p1
        additional_datasets:
          - {dataset: CanESM2}
    scripts: null
  ```
</details>

<details>
  <summary>Recipe 2 (works)</summary>
  
  ```yml
preprocessors:
  test:
    mask_landsea:
      mask_out: land
      fx_variables:
        sftof:

diagnostics:

  test:
    variables:
      tos:
        preprocessor: test
        project: CMIP5
        mip: Omon
        exp: historical
        start_year: 2000
        end_year: 2000
        ensemble: r1i1p1
        additional_datasets:
          - {dataset: CanESM2}
    scripts: null
  ```
</details>

3. For `weighting_landsea_fraction`, we had similar checks. The tool tried `sftlf` and `sftof`, and only if both had different shapes, an error was printed. Right now, due to the prioritization of `sftlf`, an error is e.g. printed for every ocean variables that is not on an atmospheric grid (thus does not match the shape of `sftlf`), even though `sftof` would work just fine.

4. As far as I can tell from the code (didn't test though!) the remaining preprocessors should behave similarly to the old version (the error messages might differ, though).

5. The following message is now printed to the log. I think we should demote this to a debug message and maybe only print the `short_name` of the fx variables as info message.

<details>
  <summary>Log</summary>

  ```
2021-05-05 08:28:29,557 UTC [14161] INFO    Using fx_files: {'sftlf': {'alias': 'CanESM2',
           'dataset': 'CanESM2',
           'diagnostic': 'test',
           'end_year': 2000,
           'ensemble': 'r0i0p0',
           'exp': 'historical',
           'filename': '/pf/b/b309141/work/CMIP5_DKRZ/CCCma/CanESM2/historical/fx/atmos/fx/r0i0p0/v20120410/sftlf/sftlf_fx_CanESM2_historical_r0i0p0.nc',
           'frequency': 'fx',
           'institute': ['CCCma'],
           'long_name': 'Land Area Fraction',
           'mip': 'fx',
           'modeling_realm': ['atmos'],
           'original_short_name': 'sftlf',
           'preprocessor': 'test',
           'project': 'CMIP5',
           'recipe_dataset_index': 0,
           'short_name': 'sftlf',
           'standard_name': 'land_area_fraction',
           'start_year': 2000,
           'units': '%',
           'variable_group': 'sftlf'},
 'sftof': {'alias': 'CanESM2',
           'dataset': 'CanESM2',
           'diagnostic': 'test',
           'end_year': 2000,
           'ensemble': 'r0i0p0',
           'exp': 'historical',
           'filename': '/pf/b/b309141/work/CMIP5_DKRZ/CCCma/CanESM2/historical/fx/ocean/fx/r0i0p0/v20130119/sftof/sftof_fx_CanESM2_historical_r0i0p0.nc',
           'frequency': 'fx',
           'institute': ['CCCma'],
           'long_name': 'Sea Area Fraction',
           'mip': 'fx',
           'modeling_realm': ['ocean'],
           'original_short_name': 'sftof',
           'preprocessor': 'test',
           'project': 'CMIP5',
           'recipe_dataset_index': 0,
           'short_name': 'sftof',
           'standard_name': 'sea_area_fraction',
           'start_year': 2000,
           'units': '%',
           'variable_group': 'sftof'}} for variable tos during step mask_landsea
  ```
</details>

Possible solution
----------------------

The main issues here are 2. and 3. I think both can be fixed if we don't raise an exception [here](https://github.com/ESMValGroup/ESMValCore/blob/fee5d541dc871efe72ab972a6a52195c452d16eb/esmvalcore/preprocessor/_ancillary_vars.py#L80-L83) and [here](https://github.com/ESMValGroup/ESMValCore/blob/fee5d541dc871efe72ab972a6a52195c452d16eb/esmvalcore/preprocessor/_ancillary_vars.py#L120-L123) if the shapes of the ancilliary files do not match the cube. If a preprocessor cannot handle the case that no fx files are found/the shapes differ, the errors should be raised in the corresponding preprocessing function.

It would be also nice to add some tests for these cases, similiar to the [ones we had before](https://github.com/ESMValGroup/ESMValCore/pull/999/files?file-filters%5B%5D=.py#diff-e57a19c9bf65c498803a124f8d455e21ea4d03ed5d1be8f51d6fa4570bb25623L56-L92).
