### ISSUE TITLE
Can we run some fixes on every Omon dataset by default?

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#1146]
Almost every time I use recipe_filler.py to automatically fill up a recipe, it finds new ocean data which often have the same set of non-compliances and fixes. They often:

- use `olevel` instead
- use latitude and longitude twice
- use `latitude`/`longitude` instead of the std_name, `lat`/`lon`

There is already a standardised fix for these mistakes which appears in several cmip6 places. Can we just add this to run it by default: 
```
class Omon(Fix):
    """Fixes for ocean variables."""

    def fix_metadata(self, cubes):
        """Fix ocean depth coordinate.

        Parameters
        ----------
        cubes: iris CubeList
            List of cubes to fix

        Returns
        -------
        iris.cube.CubeList

        """
        for cube in cubes:
            if cube.coords('latitude'):
                cube.coord('latitude').var_name = 'lat'
            if cube.coords('longitude'):
                cube.coord('longitude').var_name = 'lon'

            if cube.coords(axis='Z'):
                z_coord = cube.coord(axis='Z')
                if z_coord.var_name == 'olevel':
                    fix_ocean_depth_coord(cube)
        return cubes
```

**Comment by ledm** [comment]
For instance, there are several groups of models like the BCC models and the cesm2 models all have the same set of problems. 

Perhaps some way to apply the same set of fixes to groups of models?

**Comment by zklaus** [comment]
That seems more reasonable to me. In fact, those two models have appropriate fixes, but even though we know (pretty much) that they apply to all ocean data, we only ever apply them to individual variables as discovered.

There are a number of issues and PRs on the topic. Bottomline: I think it should be addressed within the current framework and adding a fix to these two model(families) that uses `AllVars` to apply the fixes to all `Omon` and `SImon` variables will get you a long way.

**Comment by ledm** [comment]
It's crazy how few CMIP6 datasets actually work out the box. A good exercise for a willing volunteer (cough @valeriupredoi  cough) would be to use the recipe_filler.py script to produce a simple analysis (even without a diagnostic stage) on some very common datset, like Monthly tos, then run it. 

ie: run recipe_filler.py on this sample recipe:

```
documentation:
  description: |
      Template to test fixes.

  authors:
    - demora_lee

  maintainer:
    - demora_lee

  references:
    - demora2018gmd

  projects:
    - ukesm


preprocessors:
  prep_1:
    area_statistics:
        operator: mean

diagnostics:
  # --------------------------------------------------
  # Time series diagnostics
  # --------------------------------------------------
  test_stats:
    variables:
      tos_historical:
        short_name: tos
        preprocessor: prep_1
        project: CMIP6
        mip: Omon
        exp: historical
        grid: gn
        start_year: 1990
        end_year: 2000

    scripts:
      time_plots:
        script: ocean/diagnostic_timeseries.py

```

And then try to run the resulting recipe. I promise that you will pull your hair out. 

I've been trying to do this literally all week. Some models are simply beyond fixing. For them, i wrote this script:
```
skip_models  = [      # because
    'AWI-CM-1-1-MR',  # triangular grid
    'AWI-ESM-1-1-LR', # triangular grid
    'IITM-ESM',       # No longitude bounds in irregular grid..
    'FGOALS',         # No longitude bounds in irregular grid.
    'NESM3',          # Branch time in parent is incorrect.
    'MIROC-ES2L',     # SSP data contains loads of other variables.
    ]

for m in skip_models:
    print("sed -e '/"+m+"/ s/^#*/#/' -i ", fn2)
```
Though there are probably others that don't work too.
