### ISSUE TITLE
Area statistics won't work on data with lambert Conformal projection

### ISSUE THREAD

**Issue by thomascrocker** [ESMValGroup/ESMValCore#1156]
For RCM data on a Lambert Conformal projection (see for example http://esg1.umr-cnrm.fr/thredds/fileServer/CORDEX_CNRM/output/EUR-11/CNRM/CNRM-CERFACS-CNRM-CM5/rcp85/r1i1p1/CNRM-ALADIN63/v2/3hr/tas/v20190419/tas_EUR-11_CNRM-CERFACS-CNRM-CM5_rcp85_r1i1p1_CNRM-ALADIN63_v2_3hr_200601010300-200701010000.nc ) the names of the x and y dim coordinates are `projection_x_coordinate` and `projection_y_coordinate`. I think this is a standard naming.

However, when dealing with irregular grids the code to calculate area statistics assumes that the names of these coordinates are `grid_latitude` and `grid_longitude`.
https://github.com/ESMValGroup/ESMValCore/blob/3078908caee50d4abc6a1ed4ffbbd994d594f17a/esmvalcore/preprocessor/_area.py#L242
So the calculation of area weights fails.

This can probably be fairly easily fixed by modifying the logic on that line slightly. Creating this issue so it's on my TODO list of things to sort out re CORDEX. If I get around to creating a branch that fixes this I'll update this issue.

**Comment by zklaus** [comment]
@thomascrocker, I am afraid the issue is more subtle. The names `grid_latitude` and `grid_longitude` are reserved for only rotated regular grids. That is the only kind of grid for which we have the ability to calculate the areas, so merely changing the names doesn't help, we would need to add calculation of areas. That would be a great addition, preferably to iris, but it substantial effort.

**Comment by thomascrocker** [comment]
Ah yes, I see that the `area_weights` method only supports spherical co-ordinate systems.. In which case this makes it even more important that #865 and #184 are finished. This would at least allow me to regrid the data onto a regular grid as a workaround (and to be honest is needed for other purposes anyway).
What needs to be done to move them forward?

**Comment by zklaus** [comment]
I think #865 is essentially ready, we just got a bit side-tracked in the comments. #184 needs more work, I think. Either way, these will have to wait until *after* the 2.3.0 release.

**Comment by schlunma** [comment]
Moving this to v2.6 to follow the corresponding PR.

**Comment by nhsavage** [comment]
a summary of where I think we are with this issue
1. we can't currently calculate area weights for data on lambert conformal grids because iris doesn't support this
2. we can't regrid to a regular lat/lon to allow us to bypass this issue until#184 is merged

So either:
1. we extend Iris to be able to calculate area weights (better) or
2. we complete #184 and work around the problem using regridding

Is that a good summary?

**Comment by zklaus** [comment]
@nhsavage, if we can get the `areacella` "fx" file, we should be able to read the area and make things work that way. Could you try an example with added cell area? The preprocessor section should look something like
```yaml
preprocessors:
  my_preprocessor:
    area_statistics:
      operator: mean
      fx_variables:
        areacella:
```

**Comment by nhsavage** [comment]
we can give that a go, but in general that approach is sub optimal until #1082 is merged

**Comment by nhsavage** [comment]
also - the areacella files do not appear to be uploaded for the RegCM4 family of models. This is one of the CORDEX core models and as such is a key target here (we can ask for this to be uploaded of course)

**Comment by nhsavage** [comment]
Hmm. I have been drilling down into the source code where this fails. It seems that #999 actually added the support for using cell area files already. That suggests strongly that using the fx files is a good way forward. We should try this for the original file with a more recent release of ESMValCore. 

That does add extra importance to #1082 though. 

For the models which are misisng areacella files, we can use a twin track approach, asking the modellers to upload these files to ESGF and in the short term making our own files

**Comment by zklaus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Area statistics lambert conformal](https://trello.com/c/4RG3EzyO/5-area-statistics-lambert-conformal)

**Comment by stephenworsley** [comment]
I've had a chat with @nhsavage, I believe that `iris.analysis.cartography.area_weights` can be approximated by using the back end of iris-esmf regrid using the following code:

```python
import esmf_regrid

field = esmf_regrid.schemes._cube_to_GridInfo(cube).make_esmf_field()
field.get_area()
area_weights = field.data
```

Note: that this is probably going to be an approximation since ESMF assumes all straight lines are great circle arcs. If this turns out to be a workable solution, I could look into making this a pubic utility function in iris-esmf-regrid. Also, this seems to involve iris guessing the bounds since they were not present on the file I was experimenting with.

**Comment by bouweandela** [comment]
> That does add extra importance to https://github.com/ESMValGroup/ESMValCore/pull/1082 though.

@nhsavage An alternative approach has been implemented in the end, and has been available for a while now. See [here](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html#preprocessors-using-supplementary-variables) for documentation.

**Comment by nhsavage** [comment]
I think this might now be possible using https://github.com/SciTools/iris-esmf-regrid/pull/649 but I don't currently have time to work on it. Probably only now valuable in the case where the areacella file has not been provided. I don't know if this is a common case.

**Comment by nhsavage** [comment]
probably not important except where models have failed to provide areacella. https://github.com/SciTools/iris-esmf-regrid/pull/649 looks like it would support this now. 

Worth noting that [stephenworsley](https://github.com/stephenworsley) said:

_'It should be noted that esmf_regrid.util.find_area does behave slightly differently to iris.analysis.cartography.area_weights. There is no normalize, compute or chunks arguments in find_area and find_area returns the areas, effectively, in square radians by default, though the radius of Earth can be passed in as an argument to get the same behaviour as area_weights default behaviour.'_

**Comment by bouweandela** [comment]
This works if the cell areas are provided. For example, this recipe runs fine:
```yaml
documentation:
  title: Example recipe that computes the area mean of CORDEX-CMIP5 datasets.
  description: |
    This is an example recipe that loads CORDEX-CMIP5 datasets and computes the
    area mean using the areacella variable.
  authors:
    - andela_bouwe
  maintainer:
    - andela_bouwe

preprocessors:
  tas_preprocessor:
    area_statistics:
      operator: mean

diagnostics:
  tas_europe:
    additional_datasets:
      - dataset: ALADIN63
        driver: CNRM-CERFACS-CNRM-CM5
        ensemble: r1i1p1
        institute: CNRM
        rcm_version: v1
    variables:
      tas:
        project: CORDEX
        mip: mon
        domain: EUR-11
        exp: historical
        timerange: 2003/2005
        preprocessor: tas_preprocessor
    scripts:
      script1:
        script: examples/diagnostic.py
        quickplot:
          plot_type: plot
```
and produces this figure:

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/6f97e797-405f-4330-993d-9768cb11686d" />

using these files:
```
/home/bandela/climate_data/cordex/output/EUR-11/CNRM/CNRM-CERFACS-CNRM-CM5/historical/r1i1p1/ALADIN63/v2/mon/tas/v20190510/tas_EUR-11_CNRM-CERFACS-CNRM-CM5_historical_r1i1p1_CNRM-ALADIN63_v2_mon_200101-200512.nc
/home/bandela/climate_data/cordex/output/EUR-11/CNRM/CNRM-CERFACS-CNRM-CM5/historical/r1i1p1/ALADIN63/v2/fx/areacella/v20190510/areacella_EUR-11_CNRM-CERFACS-CNRM-CM5_historical_r1i1p1_CNRM-ALADIN63_v2_fx.nc
```
For the case where the cell areas are not provided, I opened #3115.
