### ISSUE TITLE
Run preprocessor for multiple regions

### ISSUE THREAD

**Issue by Peter9192** [ESMValGroup/ESMValCore#1267]
I know at least four use cases* where it would be useful to be able to run the same preprocessing chain for multiple regions. Of course I could run the recipe multiple times, but that feels rather convoluted and moreover, I would like to be able to combine the results in the diagnostic script. Therefore it would be really nice if I could do something like

```yaml
preprocessor:
  analyse_regions:
    extract_shape:
      shapefile: shapefiles/ar6.shp
      decomposed: True
      method: contains
      crop: true
      ids:
        - 'N.Europe'
        - 'West&Central-Europe'
        - 'E.Europe'
        - 'Mediterranean'
      area_statistics:
        operator: mean
```

and get the mean field for each of the specified regions. In this case, it seems similar to `seasonal_statistics`. Perhaps leaving out the area_statistics should also be an option, but I'm not quite sure how that should behave. I guess it could produce four preprocessed cubes, one for each region, or a single cube with an additional (categorical) dimension.

I guess it could work something like the existing [iris coord categorization](https://scitools.org.uk/iris/docs/v1.9.0/html/userguide/cube_statistics.html#partially-reducing-data-dimensions), although it would have to be applied to lat and lon simulatenously. Perhaps it can be added as an optional (groupby-like) argument to `area_statistics`, although then it is tied to that specific preprocessor, while perhaps aggregation is not always desirable. 

I'm also not sure if it should work exclusively for shapefiles with multiple IDs, or that regions could be supplied as multiple shapefiles or several bounding boxes (like extract_region). 

Any ideas, suggestions, comments, or objections as to whether this is useful and how this could best be achieved?

*) the four usecases:
1. [Impact recipe](https://docs.esmvaltool.org/en/latest/recipes/recipe_impact.html), provides quick insight into model performance for selected variables. User request is to give this information more specifically for multiple regions.
2. [ClimWIP recipe](https://docs.esmvaltool.org/en/latest/recipes/recipe_climwip.html#updating-the-brunner-et-al-2019-recipe-for-new-regions), calculating weights/constraints for multiple regions. 
3. [Hydrology recipes](https://docs.esmvaltool.org/en/latest/recipes/recipe_hydrology.html), generating forcing data for multiple catchment areas
4. @thomascrocker's work on EUCP [lines of evidence](https://github.com/MetOffice/EUCP_WP5_Lines_of_Evidence)
