### ISSUE TITLE
Dataset problem: Bug with regridding and FGOALS-f3-L

### ISSUE THREAD

**Issue by thomascrocker** [ESMValGroup/ESMValCore#1270]
I've developed a diagnostic looking at SST biases from CMIP6 models. It works fine for all the models I've used it with except one. FGOALS-f3-L.
When plotting, there is a strip of blank data either side of the meridian. This isn't present for any of the other models.
![image](https://user-images.githubusercontent.com/17336982/129206183-3b058b33-fa66-445b-bb85-fa040edf6b6c.png)

The recipe uses the preprocessor to regrid the models onto the same grid as the HadISST dataset. Here is the pre processor and datasets used (it will run with other CMIP6 models, but they don't exhibit the bug). The variable used is `ts`:
```
datasets:
  - { dataset: HadISST, project: OBS, tier: 2, type: reanaly, version: 1 }
  - { dataset: FGOALS-f3-L, project: CMIP6, exp: historical, ensemble: r1i1p1f1, grid: gr, mip: Amon }

preprocessors:
  preproc:
    extract_region:
      start_longitude: -25
      end_longitude: 25
      start_latitude: -40
      end_latitude: 25
    climate_statistics:
      operator: mean
      period: season
    regrid:
      target_grid: HadISST
      scheme: linear
```
I''ve run my recipe using the `save_intermediary_cubes: true` option and examined the netCDF files created by the pre-processor. The problem manifests itself at the regrid stage. Prior to regridding the data is fine. After regridding the data from the gridboxes either side of the meridian is masked and set to the fill value of 1.e+20

This is all being run using the ESMValTool install on JASMIN.

- Data file has been changed by you in any way (if you answer yes the issue will be void and closed, we are not
supporting custom-made datasets that present problems, it is your resposability to fix those problems): No
- Project (CMIP5/CMIP6/OBS/obs4mips/etc): CMIP6
- Full dataset description (fill out as many as you know, please): See above
  - dataset: 
  - experiment:
  - mip:
  - grid:
  - type:
  - version:
  - tier:
  - variable used:
  - data version:
- Problems encountered (please describe what the actual problems are: e.g. wrong standard name, issue with dimensions):
- Pointer to existing copy of data on ESGF node (it would be very useful if you could provide a physical
fullpath to the file(s) that are causing the problem, e.g. on CEDA Jasmin or DKRZ):
- Other notes and mentions:

**Assign the right people**
If you are already a member of the ESMValTool GitHub project, please assign Valeriu Predoi (valeriupredoi) and
Klaus Zimmermann (zklaus) to the issue. They will then check the issue raised and propagate it further to the
data model developers.

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory
  - Attach a text file with the output of `ncdump -h /path/to/file.nc`

Cheers :beer:
