### ISSUE TITLE
Optional flag that if on stops the run if any of data files not found

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1282]
Was chatting to @ledm and he raised this point, with the following used case: if a certain fx file needed for a preprocessor (area, volume etc) is not found, the user should be able to turn a button on and have the run exit without continuing (in this case, the code goes on since it may be able to use the NE masks instead of the fx data). We do have the code exit if there is Missing Data, but if one uses the `--skip-nonexistent` flag it'll go on so we'd need something like `--die-hard-fx` or something so the run exits nonetheless, if certain data is not found. From my recollection it's only the fx data that doesn't stop the run if not present, is there any other type of that that has the same behavior?

**Comment by ledm** [comment]
Is there any progress on this one? It's holding up one of my analyses.

**Comment by zklaus** [comment]
I don't understand the issue. It seems at most it would stop a run. If you want to stop a run, just don't run it?

**Comment by ledm** [comment]
At the moment, if the FX files aren't found, the run proceeds anyway and breaks elsewhere (silently and ambiguously).

**Comment by zklaus** [comment]
Sure. I am not saying that this shouldn't be improved. What I don't understand is how it holds you up, since once you have understood the problem you can just move on, no?

**Comment by ledm** [comment]
The solution is to figure out exactly which models ESMValTool can't find the right fx file, then comment out all the places that those models are called. It's a manual solution to an automated problem. 

I learned very early on in my phd that anything you have to do once, you'll have to do 50 times, so automation is the only way to not waste time.

**Comment by valeriupredoi** [comment]
this conversation cracks me up :laughing: We could exit on warning, but that might exit the thing earlier, or we could define a specific exception related to FX files not found and add a flag that allows the code to exit on that exception; we could also have a proper dry-run run that finds all this guff before one runs a heavy recipe with lots of preprocessors. I like the dry-run myself, something that I implemented and have a PR open many pre-pandemic moons ago, but it seems a lot of the chieftains don't like that. Up to you to say how you'd think of a working solution @ledm then I can give you a hand implementing it :+1:

**Comment by valeriupredoi** [comment]
> I don't understand the issue. It seems at most it would stop a run. If you want to stop a run, just don't run it?

:rofl: This is the classical beer drinking paradigm: you want to drink but you don't want to get drunk

**Comment by ledm** [comment]
The dry run seems like the best option for me. I want a list of missing files whose absence will break the run. 

I'm going to doing this same analysis multiple times on a set of like 7 different variables, each one includes 200-500 datasets. CBA to run, break,fix, run,break, fix, run break fix, ad infinitum for the next several weeks/months.

**Comment by ledm** [comment]
This whole thing has uncovered another problem with finding the fx files. Here's what I think the problem is. The NCAR/CESM2-WACCM model has provided Ofx for both `historical` and `piControl` experiements. However, the `areacello` is only in the piControl, not in the historical one!

ie:
```
$ ls /badc/cmip6/data/CMIP6/CMIP/NCAR/CESM2-WACCM/*/r1i1p1f1/Ofx/

/badc/cmip6/data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r1i1p1f1/Ofx/:
sftof

/badc/cmip6/data/CMIP6/CMIP/NCAR/CESM2-WACCM/piControl/r1i1p1f1/Ofx/:
areacello  deptho  sftof  volcello

```

When I run the preprocessor/diagnostic below, the fx finder is unable to locate the arecello fx files. I think the presences of an Ofx directory in historical confuses the FX finder. 
 
Here's my preprocessor:
```
  prep_profile_2:
    area_statistics:
      fx_variables:
      - {activity: CMIP,  grid: gn, mip: Ofx, short_name: areacello}
      operator: mean
```

And the diagnostic:
```
diagnostics:
  diag_timeseries_3:
    scripts:
      Model_range_polots: script: ocean/diagnostic_timeseries.py
    variables:
      tos_profile_hist:
        additional_datasets:
        - {dataset: CESM2-WACCM, end_year: 2010, ensemble: r1i1p1f1, exp: historical, grid: gn, mip: Omon, project: CMIP6, start_year: 2000}
        mip: Omon
        preprocessor: prep_profile_2
        short_name: thetao
```

**Comment by valeriupredoi** [comment]
> The dry run seems like the best option for me. I want a list of missing files whose absence will break the run.
> 
> I'm going to doing this same analysis multiple times on a set of like 7 different variables, each one includes 200-500 datasets. CBA to run, break,fix, run,break, fix, run break fix, ad infinitum for the next several weeks/months.

this looks like a corner case that should have been taken care of by merging https://github.com/ESMValGroup/ESMValCore/pull/1216 - please open a separate issue and assign @schlunma and @sloosvel :beer:

**Comment by schlunma** [comment]
I don't think so, #1216 took care of the case when no `mip` is given:

https://github.com/ESMValGroup/ESMValCore/blob/8cd5dcfd7af0b43eedcf9b8b2de2dd44502cb28a/esmvalcore/_recipe.py#L416-L420

Since the `mip` is specified in the example that @ledm showed here, this does not apply.

**Comment by valeriupredoi** [comment]
@schlunma right you are! The mip is given, but the data dir is empty, OK this is a double bug - our code being confused by that and the data missing on JASMIN. Anyways, let's take this discussion to the relevant issue :+1:

**Comment by valeriupredoi** [comment]
actually - where are you running @ledm ? I am on JASMIN and I see all's fine in the `historical` Ofx dir:
```
[valeriu@sci2 ~]$ ls -la /badc/cmip6/data/CMIP6/CMIP/NCAR/CESM2-WACCM/*/r1i1p1f1/Ofx/areacello/gn/latest
lrwxrwxrwx 1 badc badcint 9 Aug 10  2020 /badc/cmip6/data/CMIP6/CMIP/NCAR/CESM2-WACCM/1pctCO2/r1i1p1f1/Ofx/areacello/gn/latest -> v20190425
lrwxrwxrwx 1 badc badcint 9 Apr 12  2019 /badc/cmip6/data/CMIP6/CMIP/NCAR/CESM2-WACCM/piControl/r1i1p1f1/Ofx/areacello/gn/latest -> v20190320
```

**Comment by ledm** [comment]
So, by brute forcing the problem, I've come up with a list of models that do not work in ESMValTool for this calculation. Either because their grids are weird, the FX files are missing, or there's challenging problems in their netcdfs. It's fully described in the discussion here:

https://github.com/ESMValGroup/ESMValTool/discussions/2308

**Comment by bouweandela** [comment]
Would it be an option to make the recipe more specific about specifying ancillary/cell measure variables? Elsewhere I proposed the following syntax:
```yaml
preprocessors:
  area_stats:
    area_statistics:
      operator: mean

variables:
  tos:
    project: CMIP6
    mip: Omon
    preprocessor: area_stats
    exp: historical
    ensemble: r1i1p1f1
    grid: gn
    ancillary_variables:
      - {short_name: areacello, optional: false}
      - {short_name: sftlf, mip: fx, optional: true}
    additional_datasets:
      - dataset: ACCESS-CM2
      - dataset: ACCESS-ESM1-5
      - dataset: AWI-CM-1-1-MR
      ..
```
or if different `mip`s or other settings are needed per dataset:
```yaml
preprocessors:
  area_stats:
    area_statistics:
      operator: mean

variables:
  tos:
    project: CMIP6
    mip: Omon
    preprocessor: area_stats
    exp: historical
    ensemble: r1i1p1f1
    grid: gn
    additional_datasets:
      - dataset: ACCESS-CM2
        ancillary_variables:
          - {short_name: areacello, mip: fx, optional: false}
      - dataset: ACCESS-ESM1-5
        ancillary_variables:
          - {short_name: areacello, optional: false}
      ..
```
This would make it possible to specify the ancillary/cell measure variables needed per variable and per dataset. The ancillary variables would inherit all the key-value pairs from the variable/dataset they belong to.

We could add an `optional: true` or `false` option to make an ancillary/cell measure variable optional. I'm not sure what the most sensible default would be, could be discussed and be different per preprocessor function or variable as long as it's consistent and well documented.

**Comment by ledm** [comment]
I'm onboard with this solution. I think this would add the flexibility that I needed.

**Comment by zklaus** [comment]
Hm. I like the approach better and think it would be clearer, but I am not sure it enables something that is functionally impossible at the moment. So I'd rather we understand the actual problem before we code a new solution.

**Comment by bouweandela** [comment]
Another alternative, more consistent with the way variables are defined:
```yaml
preprocessors:
  area_stats:
    area_statistics:
      operator: mean

variables:
  tos:
    project: CMIP6
    mip: Omon
    preprocessor: area_stats
    exp: historical
    ensemble: r1i1p1f1
    grid: gn
    additional_datasets:
      - dataset: ACCESS-CM2
        ancillary_variables:
          areacello:
            mip: fx
            optional: false
      - dataset: ACCESS-ESM1-5
        ancillary_variables:
          areacello:
            optional: false
      ..
```
or even:
```yaml
preprocessors:
  area_stats:
    area_statistics:
      operator: mean

variables:
  tos:
    project: CMIP6
    mip: Omon
    preprocessor: area_stats
    exp: historical
    ensemble: r1i1p1f1
    grid: gn
    additional_datasets:
      - dataset: ACCESS-CM2
        ancillary_variables:
          cell_area:
            short_name: areacello
            mip: fx
            optional: false

```
