### ISSUE TITLE
Add support for extracting a specific point by location name

### ISSUE THREAD

**Issue by jvegreg** [ESMValGroup/ESMValCore#1334]
It would be nice to have the option to specify the point we want to extract with just the location name and not the coordinates. It will save most users one search and will make recipes more readable.

So for example, this preprocessor from the `recipe_python.yaml`
```yaml
  annual_mean_amsterdam:
    extract_point:
      latitude: 52.379189
      longitude: 4.899431
      scheme: linear
    annual_statistics:
      operator: mean
    multi_model_statistics:
      statistics:
        - mean
      span: overlap
```
will be just

```yaml
  annual_mean_amsterdam:
    extract_location:
      location: Amsterdam
      scheme: linear
    annual_statistics:
      operator: mean
    multi_model_statistics:
      statistics:
        - mean
      span: overlap
```

There is already a PR open in #1251 with implements this using openstreetmap nominatim through geopy and delegates the extraction itself to the `extract_point` preprocessor
