### ISSUE TITLE
fx variables in defined in preprocessor section are not augmented with extra_facets

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1398]
fx variables defined in the preprocessor, e.g.,

```yml
  area_mean:
    area_statistics:
      operator: mean
      fx_variables:
        areacella:
          mip: fx
```

are not [augmented](https://github.com/ESMValGroup/ESMValCore/blob/e4d61adfb14e3a3995abe2eb869d5f1781053416/esmvalcore/_recipe.py#L105-L109) with `extra_facets`, which might lead to failing fixes.

This can be fixed by adding `_add_extra_facets` to the following function:

https://github.com/ESMValGroup/ESMValCore/blob/e4d61adfb14e3a3995abe2eb869d5f1781053416/esmvalcore/_recipe.py#L331-L344
