### ISSUE TITLE
Tracing a file's ancestry

### ISSUE THREAD

**Issue by znicholls** [ESMValGroup/ESMValCore#1572]
**Is your feature request related to a problem? Please describe.**

Related to #1161, I have a question about esmvaltool's capacity to link back through a file's 'ancestry'. I've done work on this in another package (gitlab.com/znicholls/netcdf-scm, paper here https://rmets.onlinelibrary.wiley.com/doi/10.1002/gdj3.113) because esmvaltool wasn't mature enough at that stage to be a viable solution. Now it looks awesome (congrats) so I was wondering if porting some of the functionality in would be helpful.

To keep things simple, let's here just focus on traversing a file's ancestry. For example, I have a G6solar file, whose parent is ssp585, grandparent is historical and great-grandparent is piControl. In some cases, all the files will have the same ensemble member id (e.g. r1i1p1f1) but sometimes the parent might be from a different ensemble member (e.g. G6solar is r3i1p1f1 and ssp585 is r1i1p1f1). 

EDIT: answered in docs (my bad) ~~*First question:* Is esmvaltool currently able to traverse such a history and create a continuous timeseries? My impression is that it can join experiments with the same ensemble member using a syntax like `  - {dataset: UK-ESM1-LL, project: CMIP6 exp: [historical, ssp585, G6solar], ensemble: r1i1p1f1}` but I'm guessing you can't do ```  - {dataset: UK-ESM1-LL, project: CMIP6 exp: [historical, ssp585, G6solar], ensemble: [r1i1p1f1, r1i1p1f1, r3i1p1f1]}``` ?~~

*Second question:* Is esmvaltool able to handle experiment overlap appropriately? For example, you need to use ssp585 to bridge the gap between the end of historical (2014) and the start of G6solar (2019 from memory) but a straight time concatenation doesn't work because you end up with both ssp585 and G6solar data (from e.g. 2019 to 2100). 

I'm not sure what the best way to implement this would be. If I were doing it now, I would try something like:

1. define my files of interest in a recipe
2. download them using esmvaltool 
3. work out their parents using a custom script, writing a new recipe in the process
5. download the parents using esmvaltool
6. work out grandparents using a custom script, writing a new recipe in the process
7. download grandparents using esmvaltool
8. etc. until I get back to piControl
9. write a recipe based on all the child datasets with a diagnostic that joins them to their ancestry appropriately

**Would you be able to help out?**

Yes (the motivation for me is that it would be great to port this functionality into a maintained project that has all the other benefits of esmvaltool and its community rather than leaving them in a drifting package with a maintenance team of 2).

**Comment by znicholls** [comment]
fyi @lewisjarednz

**Comment by znicholls** [comment]
> First question:

Ignore my first question, I've just read the docs properly

**Comment by znicholls** [comment]
Re the second question, I just tried the recipe below:

<details>
  <summary>Test recipe</summary>

```yaml
# ESMValTool
# recipe_concatenate_exps.yml
---
documentation:
  description: |
    Concatenate time series of different experiments at the preprocessor level.

  title: Recipe to test time concatenation in preprocesor.

  authors:
    - schlund_manuel

  maintainer:
    - schlund_manuel

datasets:
  - {dataset: CESM2-WACCM, grid: gn, ensemble: r1i1p1f1, activity: [GeoMIP, ScenarioMIP, CMIP]}
#  - {dataset: CNRM-ESM2-1}
#  - {dataset: IPSL-CM6A-LR}
#  - {dataset: MPI-ESM1-2-LR}
#  - {dataset: UKESM1-0-LL}


diagnostics:

  diag_concatenate_exps:
    description: Concatenate historical, SSP5-8.5 and G6solar data
    variables:
      tas:
        project: CMIP6
        mip: Amon
        start_year: 1850
        exp: [historical, ssp585, G6solar]
        end_year: 2100
    scripts: null
```

</details>

It gives the following output, which I think shows that the concatenation doesn't work unfortunately because of the overlap between experiments.

<details>
  <summary>Test recipe output once plotted (annual-mean)</summary>

<img width="665" alt="image" src="https://user-images.githubusercontent.com/23625371/167280284-844918b2-aecf-4c05-89f9-bda7baf1a484.png">

</details>

I think the issue is in https://github.com/ESMValGroup/ESMValCore/blob/5d5ddddd633024dee741f54768d44d32023f3a73/esmvalcore/preprocessor/_io.py#L183 and its interaction with https://github.com/ESMValGroup/ESMValCore/blob/5d5ddddd633024dee741f54768d44d32023f3a73/esmvalcore/preprocessor/_io.py#L388. This just joins everything starting from the oldest experiment (i.e. historical) and always picking the longer cube so we end up with ssp585 from 2019-2068 instead of G6solar (because the G6solar experiment comes in two files whereas ssp585 is all in one so the longer ssp585 file gets picked instead of the first, shorter G6solar one). To fix it I think you'd have to know that G6solar was the experiment you were actually interested in and use the branch points to pick the appropriate subset of the parent experiments rather than the current concatenation algorithm.
