### ISSUE TITLE
Sea Ice Extent as a derived variable

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#1693]
**Is your feature request related to a problem? Please describe.**
The sea ice extent is computed by summing `areacello` over the points in which `siconc/sic` (sea_ice_area_fraction) has values > 15%.

It would be useful to be able to compute this quantity as a derived variable and reduce the amount of data that is stored after the preprocessing. The derivation could  return an array of ones, with masked values where the sea ice area fraction  has values < 15%.  This array could later be used in combination with `area_statistics(operator='sum')` in order to obtain the true sea ice extent, since areacello would be used as the weights to compute the weighted sum.

Units of the derived variable should be set to 'm2', since area_statistics does not handle very well the resulting units. 
In summary, with the addition of the derived variable, the sea ice extent could be computed at preprocessor level using a recipe such as:

```yaml
preprocessor:
  preproc:
    # extract_region / extract_shape (in order to obtain regional values)
    area_statistics:
      operator: 'sum'
   # extra time operations if needed
    convert_units:
      units: 10^6 km2 # the units we ultimately use

variables:
  siextent:
    derive: true
    preprocessor: preproc
  
```
Where the derivation would consist of:

```python
        siconc = cubes.extract_cube(Constraint(name='sea_ice_area_fraction'))
        ones = da.ones_like(siconc)
        siextent_data = da.ma.masked_where(siconc.lazy_data()<15, ones)
        siextent = siconc.copy(siextent_data)
        siextent.units = 'm2'
```

**Would you be able to help out?**
Yes
