### ISSUE TITLE
Change default DRS for native ICON output

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1707]
While working with new ICON data I discovered that the current DRS

```yaml
  input_dir:
    default: '{version}_{component}_{exp}_{grid}_{ensemble}'
  input_file:
    default: '{version}_{component}_{exp}_{grid}_{ensemble}_{var_type}*.nc'
  output_file: '{dataset}_{version}_{component}_{grid}_{mip}_{exp}_{ensemble}_{short_name}_{var_type}'
```

is not general enough to cover all possible input files. This PR changes this to the more general syntax:

```yaml
  input_dir:
    default:
      - '{exp}'
      - '{exp}/outdata'
  input_file:
    default: '{exp}_{var_type}*.nc'
  output_file: '{project}_{dataset}_{exp}_{var_type}_{mip}_{short_name}'
```

This change will **note be backward compatible**, but with an [easy change](https://github.com/ESMValGroup/ESMValCore/pull/1705#issuecomment-1222511627) old recipes can be fixed. I know that this is not optimal, but I believe that the easier syntax in this new version and the greater flexibility justify this change.

Please note that this only applies to native ICON output (`project: ICON, dataset: ICON`), other output (e.g., also ICON output from CMIP6) is not affected.
