### ISSUE TITLE
Provenance tracking in `mask_multimodel` is slow and needs a lot of memory

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1981]
EDIT: The reason for the issue below is the provenance tracking (see this [comment](https://github.com/ESMValGroup/ESMValCore/issues/1981#issuecomment-1478107436)).

While developing a new recipe, @bettina-gier and I found something very weird. A recipe that previously finished in 6 min did not finish in 8 hours after adding the `mask_multimodel` preprocessor.

This can be reproduced with the following simple recipe:

<details>
<summary>Example recipe</summary>

```yml
# ESMValTool
---
documentation:
  title: test
  description: test
  authors:
    - schlund_manuel

preprocessors:

  test:
    mask_landsea:
      mask_out: sea
    regrid:
      target_grid: 2x2
      scheme: nearest
    mask_multimodel:

diagnostics:

  diag_test:
    variables:
      tas:
        preprocessor: test
        project: CMIP5
        ensemble: r1i1p1
        mip: Amon
        exp: historical
        start_year: 2000
        end_year: 2004
        additional_datasets:
          - {dataset: ACCESS1-0}
          - {dataset: BNU-ESM}
          - {dataset: CanESM2}
          - {dataset: CCSM4}
          - {dataset: CNRM-CM5}
          - {dataset: CSIRO-Mk3-6-0}
          - {dataset: GFDL-ESM2M}
          - {dataset: HadGEM2-ES}
          - {dataset: GISS-E2-R}
          - {dataset: inmcm4}
          - {dataset: IPSL-CM5B-LR}
          - {dataset: MIROC-ESM}
          - {dataset: MPI-ESM-LR}
          - {dataset: MRI-CGCM3}
          # - {dataset: NorESM1-M}
    scripts:
      null
```
</details>

When varying the number of datasets, I get the following behavior of the maximum memory usage and run time (note that all runs were performed on the same interactive Levante node):

![mem](https://user-images.githubusercontent.com/32543114/226639599-63ba508f-f32a-4bc9-b058-785b271529dc.png)

![time](https://user-images.githubusercontent.com/32543114/226639627-b5aa4938-b0d8-4831-8d89-4f23ba05b837.png)

These are clearly exponential relationships! No wonder this results in a timeout with 20+ models...Good news is that the exponential behavior is already present in v2.7.0 (so no need to investigate that right now), but v2.8.0rc2 has made it worse by a factor of ~1.5.

As you can see by the baseline runs, removing any of the masking preprocessors [`mask_multimodel`](https://github.com/ESMValGroup/ESMValCore/blob/14408c35bc9eb24c27799eb1bab1e6563c7cc75c/esmvalcore/preprocessor/_mask.py#L524) or [`mask_landsea`](https://github.com/ESMValGroup/ESMValCore/blob/14408c35bc9eb24c27799eb1bab1e6563c7cc75c/esmvalcore/preprocessor/_mask.py#L68) fixes this issue.

Couple of thoughts about this:

- I don't see any obvious problem with the code of `mask_multimodel` (which is fully lazy). However, `mask_landsea` is currently not fully lazy (there are a couple of usages of `cube.data`). I tried to make it fully lazy, but ran into the same issue.
- I also tried the opposite: making the code of the two preprocessors non-lazy, which did not help. I also tried realizing the cube data right after loading the data in `esmvalcore.preprocessor._io.load`, but also did not see any difference.
- Assuming each of these datasets is 1x1° (in reality the resolution is lower), then we would have ~16 MB for the 5 years. For all 155 years of the historical simulation, this would be ~500 MB. Even if we loaded all 155 years of all models into memory, this would result in 7 GB of RAM, which is much smaller than the 16 GB currently used by v2.8.0.rc2. After adding a couple of more models, this discrepancy gets more and more ridiculous.
- I replaced `mask_multimodel` with `multi_model_statistics` and `mask_fillvalues`; in both cases I did not encounter the problem.

@ESMValGroup/esmvaltool-coreteam does anyone have an idea what could cause this behavior? My first guess would be that dask is doing something weird, but why does the issue persist if the data is realized right after loading?

And why did the run time and memory increase so much from v2.7.0 to v2.8.0rc2? The difference is always ~1.5 regardless of the number of models, so I am pretty sure this is also related to the actual preprocessing and not to data finding or something similar.

**Comment by bettina-gier** [comment]
Just inserting myself - even when I removed the mask_landsea and only tried to run with mask_multimodel my run would just hang randomly, no more output after the log saying it's starting the mask_multimodel step if using a larger amount of models (ran fine but with a lot of memory consumption with lower models). In that recipe I had 
```
  preproc:
    weighting_landsea_fraction:
      area_type: land
    regrid:
      target_grid: 2x2
      scheme: linear
    mask_multimodel:
```
preprocessors - but the weighting doesn't do masking so shouldn't hinder mask_multimodel at all!
