### ISSUE TITLE
New preprocessor: calculate statistics over regions defined by shape files

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#2007]
It would be nice to have a preprocessor that calculates arbitrary statistics over regions defined by a given shape file. For example, this preprocessor would be able to calculate surface temperature means for each [AR6 region](https://doi.org/10.5194/essd-12-2959-2020) from a regular gridded cube.

I will try to implement that.

**Comment by schlunma** [comment]
I just realized that this is already possible with our current set of preprocessors!

Successfully tested with

```yaml
regional_mean:                                                                                                                                                                                                                                                               
    extract_shape:                                                                                                                                                                                                                                                             
      shapefile: ar6                                                                                                                                                                                                                                                           
      crop: true                                                                                                                                                                                                                                                               
      decomposed: true                                                                                                                                                                                                                                                         
      ids:                                                                                                                                                                                                                                                                     
        Name: &regions_to_extract                                                                                                                                                                                                                                              
          - N.Europe                                                                                                                                                                                                                                                           
          - West&Central-Europe                                                                                                                                                                                                                                                
          - Mediterranean                                                                                                                                                                                                                                                      
          - Equatorial.Pacific-Ocean                                                                                                                                                                                                                                           
          - Equatorial.Atlantic-Ocean                                                                                                                                                                                                                                          
          - Equatorial.Indic-Ocean                                                                                                                                                                                                                                             
    area_statistics:                                                                                                                                                                                                                                                           
      operator: mean
```

This creates an output file with an additional dimension `shape_id` of length 6 (for the 6 regions given) that contains the means over these regions. :rocket:
