### ISSUE TITLE
Preprocessor `regrid` creates missing values at 90/-90 lat for some models 

### ISSUE THREAD

**Issue by LisaBock** [ESMValGroup/ESMValCore#2029]
Applying preprocessor `regrid` introduces missing values at the 90 and -90 latitude band for some models in the preprocessed files.

affected models:
'CNRM-CM6-1', 'CNRM-ESM2-1', 'CSIRO-Mk3-6-0', 'CanESM5','MIROC-ESM', 'NESM3', 'MIROC-ES2L', 'MIROC5', 'MIROC6','bcc-csm1-1', 'BNU-ESM', CanESM2', 'MPI-ESM-LR', 'MPI-ESM-MR', 'MPI-ESM1-2-LR'

I used the following preprocessor and dataset:

```
datasets:
  - {dataset: CanESM5, exp: piControl, ensemble: r1i1p1f1, grid: gn, start_year: 5201, end_year: 5350}

preprocessors:
  regrid:
    regrid:
      target_grid: 2x2
      scheme: linear

diagnostics:
  feedback_high_ECS:
    title: cloud feedback
    description: Calculate grid-level CRE feedback parameters
    variables:
      netcre_grid_level:
        short_name: netcre
        preprocessor: regrid
        project: CMIP6
        mip: Amon
        derive: true
    scripts: null
```
