### ISSUE TITLE
Inconsistency in `dataset` naming for CORDEX: download vs fixes

### ISSUE THREAD

**Issue by ljoakim** [ESMValGroup/ESMValCore#2032]
There seems to be an inconsistency regarding what the `dataset` key should contain for a CORDEX project dataset.

- For download to work, `dataset` value must contain only the name of the rcm (e.g. `RCA4`), which is mapped to `rcm_name` in the facet used for download
- In order for the correct dataset fixes to be applied (i.e. for the correct file in `_fixes/cordex` to be imported), `dataset` must contain the institute id and rcm name concatenated with a dash (e.g. `SMHI-RCA4`).

Compare the `dataset` value in the tests for the two cases, which shows the difference:

Download test (look for the CORDEX test):
`tests/integration/esgf/test_search_download.py`

and any of the CORDEX `_fixes` tests, e.g.:
`tests/integration/cmor/_fixes/cordex/test_ichec_ec_earth.py`

Running the following recipe completes as a successful run, but the program never enters `TimeLongName.fix_metadata(...)` in `esmvalcore/cmor/_fixes/cordex/cordex_fixes.py` which should be used by this dataset:

```
documentation:
  description: CORDEX download example
  title: CORDEX download example
  authors:
    - righi_mattia

datasets:
- {dataset: RCA4, project: CORDEX, domain: EUR-11,
     exp: historical, ensemble: r12i1p1,
     mip: mon, institute: SMHI, rcm_version: v1,
     driver: ICHEC-EC-EARTH, version: v20131026}

diagnostics:
  map:
    description: EUR-11 map of temperature in January 2000.
    variables:
      tas:
        timerange: 2000/P1M
    scripts:
      script1:
        script: examples/diagnostic.py
        quickplot:
          plot_type: pcolormesh
          cmap: Reds
```

**Comment by bouweandela** [comment]
My first thought would be to just rename the currently implemented fixes so they do not contain the institute anymore, e.g. rename `esmvalcore/cmor/_fixes/cordex/cnrm_cerfacs_cnrm_cm5/cnrm_aladin63.py` to `esmvalcore/cmor/_fixes/cordex/cnrm_cerfacs_cnrm_cm5/aladin63.py`, but maybe I'm missing something.

@sloosvel Is there a reason why the institute has been prefixed to the dataset name in the filenames of the currently implemented CORDEX fixes?

**Comment by sloosvel** [comment]
Yes, we wrote those based on the data available on DKRZ-Levante, which is following the BADC DRS that is specified in the configs:

```yaml
drs:
  CMIP6: DKRZ
  CMIP5: DKRZ
  CMIP3: DKRZ
  CORDEX: BADC
  obs4MIPs: default
  ana4mips: default
  OBS: default
  OBS6: default
  native6: default
...
CORDEX:
  input_dir:
    default: '/'
    spec: '{domain}/{institute}/{driver}/{exp}/{ensemble}/{dataset}/{rcm_version}/{mip}/{short_name}'
    BADC: '{domain}/{institute}/{driver}/{exp}/{ensemble}/{dataset}/{rcm_version}/{mip}/{short_name}/{version}'
    ESGF: '{project.lower}/output/{domain}/{institute}/{driver}/{exp}/{ensemble}/{dataset}/{rcm_version}/{frequency}/{short_name}/{version}'
  input_file: '{short_name}_{domain}_{driver}_{exp}_{ensemble}_{dataset}_{rcm_version}_{mip}*.nc'
  output_file: '{project}_{dataset}_{rcm_version}_{driver}_{domain}_{mip}_{exp}_{ensemble}_{short_name}'
  cmor_type: 'CMIP5'
  cmor_path: 'cordex'
```

In DKRZ, an input dir path looks like this:

```
EUR-11/SMHI/ICHEC-EC-EARTH/historical/r12i1p1/SMHI-RCA4/v1/mon/tas/
```
and an input filename like this:
```
tas_EUR-11_ICHEC-EC-EARTH_historical_r12i1p1_SMHI-RCA4_v1_mon_200101-200512.nc
```

So the `dataset` tag corresponds to the full `SMHI-RCA4` entry. I know the institute tag seems to be repeated, but it's how the data was stored and how the config developer file was set. I don't have access to BADC any more, so I don't know if what's in DKRZ matches what's in there. 

By renaming the fixes, an entry for DKRZ that includes the `{institute}-{dataset}` tags should be added in the configs as well because otherwise the data will not be found any more.  Either that or I am not sure if it's possible to ask for DKRZ data to be moved.
