### ISSUE TITLE
Dataset problem: MIROC6 salinity contains zlev and sigma, which break fix with "unknown" units

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#2174]
**Describe the dataset issue**

On jasmin, the MIROC6 salinity file contains several other datasets, not just the salinty `so`:
```
/badc/cmip6/data/CMIP6/CMIP/MIROC/MIROC6/historical/r10i1p1f1/Omon/so/gn/v20190311/so_Omon_MIROC6_historical_r10i1p1f1_gn_201001-201412.nc
```
contains:
```
[<iris 'Cube' of sea_water_salinity / (0.001) (time: 120; ocean sigma over z coordinate: 63; -- : 256; -- : 360)>,
 <iris 'Cube' of vertical coordinate formula term: zlev(k+1/2) / (unknown) (ocean sigma over z coordinate: 63; -- : 2)>,
 <iris 'Cube' of vertical coordinate formula term: sigma(k+1/2) / (unknown) (ocean sigma over z coordinate: 63; -- : 2)>,
 <iris 'Cube' of Sea Floor Depth: formula term: thetao / (m) (-- : 256; -- : 360)>]
```

Even though I don't need them (or want them or ask for them), these dataset break esmvalcore (the current main branch), as they have incorrect units (unknown). 

- ProjectCMIP6
- Full dataset description (fill out as many as you know, please):
  - MIROC6
  - historical
  - Omon
  - gn
  - r10i1p1f1
  - v20190311:
  - so

Here's a recipe:
```
diagnostics:
  diag_timeseries_3:
    scripts:
      Model_range_polots: {script: ocean/diagnostic_ai_plots.py}
    variables:
      sos_profile_hist:
        additional_datasets:
        - {dataset: MIROC6, end_year: 2010, ensemble: r10i1p1f1, exp: historical,grid: gn, mip: Omon, project: CMIP6, start_year: 2000}
        - {dataset: MIROC6, end_year: 2010, ensemble: r1i1p1f1, exp: historical, grid: gn,mip: Omon, project: CMIP6, start_year: 2000}
        - {dataset: MIROC6, end_year: 2010, ensemble: r2i1p1f1, exp: historical, grid: gn,mip: Omon, project: CMIP6, start_year: 2000}
        - {dataset: MIROC6, end_year: 2010, ensemble: r3i1p1f1, exp: historical, grid: gn,mip: Omon, project: CMIP6, start_year: 2000}
        - {dataset: MIROC6, end_year: 2010, ensemble: r4i1p1f1, exp: historical, grid: gn,mip: Omon, project: CMIP6, start_year: 2000}
        - {dataset: MIROC6, end_year: 2010, ensemble: r5i1p1f1, exp: historical, grid: gn,mip: Omon, project: CMIP6, start_year: 2000}
        - {dataset: MIROC6, end_year: 2010, ensemble: r6i1p1f1, exp: historical, grid: gn,mip: Omon, project: CMIP6, start_year: 2000}
        - {dataset: MIROC6, end_year: 2010, ensemble: r7i1p1f1, exp: historical, grid: gn,mip: Omon, project: CMIP6, start_year: 2000}
        - {dataset: MIROC6, end_year: 2010, ensemble: r8i1p1f1, exp: historical, grid: gn,mip: Omon, project: CMIP6, start_year: 2000}
        - {dataset: MIROC6, end_year: 2010, ensemble: r9i1p1f1, exp: historical, grid: gn,mip: Omon, project: CMIP6, start_year: 2000}
        end_year: 2010
        exp: historical
        grid: gn
        mip: Omon
        preprocessor: prep_profile_2
        project: CMIP6
        short_name: so
        start_year: 2000
        supplementary_variables: &ofx
                  - {short_name: areacello, mip: Ofx, exp: '*',activity: '*', ensemble: '*'}

documentation:
  title: "TEST MIROC6 salinity"
  authors: [demora_lee]
  description: "TEST MIROC6 salinity"
  maintainer: [demora_lee]
  projects: [ukesm]
  references: [demora2018gmd]

preprocessors:
  # --------------------------------------------------
  # Depth-profile preprocessors
  # --------------------------------------------------
  prep_profile_2: # For a regional profile
    area_statistics:
      operator: mean
    extract_levels:
        scheme: linear
        levels: [0.5, 1., 5., 10., 50., 100., 200., 300., 400., 500., 600., 700., 800., 900., 1000.,
                     1500., 2000., 2500., 3000., 3500., 4000.,4500., 5000.]
```

Cheers :beer:
