### ISSUE TITLE
Performance improvement: recipe_extremes_wind_3h.yml

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#2301]
This issue keeps track of the performance improvements implemented for [recipe_extremes_wind_3h.yml
](https://github.com/ESMValGroup/ESMValCore/files/13947203/recipe_extremes_wind_3h.txt) reported in https://github.com/ESMValGroup/ESMValCore/issues/1915#issuecomment-1813183100 as part of the [ESiWACE3 service project](https://www.esiwace.eu/services/software-support).

## Settings

To run the recipe, the following settings are used:

`~/.esmvaltool/config-user.yml`
```yaml
max_parallel_tasks: 1
```

`~/.esmvaltool/dask.yml`
```yaml
cluster:
  type: dask_jobqueue.SLURMCluster
  queue: compute
  account: bd0854
  cores: 128
  memory: 256GiB
  processes: 32
  interface: ib0
  local_directory: /scratch/b/b381141/dask-tmp
  n_workers: 32
  walltime: '8:00:00'
```

## Profiling

A smaller version of the recipe was used for profiling runs. It uses only the `wind_fut` variable.

Conda environment used for profiling: [environment.yml](https://github.com/ESMValGroup/ESMValCore/files/14024498/environment.txt).

The profiles attached below were created with [py-spy](https://github.com/benfred/py-spy) using the command
```bash
py-spy record \
--idle \
--rate 10 \
--subprocesses \
--format speedscope \
esmvaltool run recipe_extremes_wind_3h.yml
```
and can be viewed with https://www.speedscope.app:

1) Initial run [profile_recipe_extremes_wind_3h.json](https://github.com/ESMValGroup/ESMValCore/files/13947244/profile_recipe_extremes_wind_3h.json) (40 minutes)
1) Faster https://github.com/SciTools/iris/pull/5691 [profile](https://github.com/ESMValGroup/ESMValCore/files/14025729/profile_recipe_extremes_wind_3h_faster_print.json)
...
1) `main` iris and ESMValCore branch on 2024-09-12 runs including #2517 and #2522: [single node (8 minutes)](https://github.com/user-attachments/files/16984508/recipe_extremes_wind_3h_1node.json), [2 nodes (5:20 minutes)](https://github.com/user-attachments/files/16984523/recipe_extremes_wind_3h_2nodes.json), [4 nodes (3:20 minutes)](https://github.com/user-attachments/files/16984532/recipe_extremes_wind_3h_4nodes.json)
