### ISSUE TITLE
Adjusting `extract_time` to make year optional

### ISSUE THREAD

**Issue by malininae** [ESMValGroup/ESMValCore#2304]
Almost ready to submit an extreme event diagnostic. To make the current diagnostic to be applicable for a wider range of applications, I suggest to create a preprocessor `extract_day_range(start_day, end_day)` which would extract a range of days from `start_day` to `end_day` in each year (similar to `extract_month`). I tested it in the diagnostic, extracting constrains in iris and it works. I will try to make it happen in the next weeks.

**Comment by bouweandela** [comment]
It would probably be easiest to modify the `extract_time` preprocessor function so the month and year arguments are optional.

**Comment by valeriupredoi** [comment]
I agree with @bouweandela - next thing you know, when NGMS comes about, we'll want an `extract_millisecond_range` preprocessor too :grin:

**Comment by malininae** [comment]
@bouweandela @valeriupredoi sounds good, I though before to adjust `exctract_month` but you suggestion is way better :smiley: The only issue, currently my recipe looks like [that](https://github.com/malininae/ESMValTool/blob/extremes_bc/esmvaltool/recipes/malinina23/recipe_bc_extremes_txx.yml), and I already use extract time, however I might be able to switch to `clip_timerange` not to repeat the preprocessors.

**Comment by bouweandela** [comment]
If you specify a `timerange` or `start_year`/`end_year` for a variable or dataset, `clip_timerange` will be used automatically.

**Comment by malininae** [comment]
> If you specify a `timerange` or `start_year`/`end_year` for a variable or dataset, `clip_timerange` will be used automatically.

True, the problem is that I'm interested in the data from, e.g., 2011-2030, but since I need anomalies with the 1940-1969 base period, I have to use `start_year: 1940, end_year: 2030` timeseries and then `extract_timerange` from 2011 to 2030, otherwise I get an error. It is an issue with `anomalies` preprocessor I've noticed a while ago, but I've never opened an issue about it (will do it shortly). Please, let me know if you have a better solution in mind.

**Comment by malininae** [comment]
Ok I tried following:
```
# ESMValTool
# recipe_bc_extremes_txx.yml
---
documentation:

  title: GEVs 2021 BC heatwave

  description: This is a recipe for analysing 2021 BC heat wave.

  authors:
    - malinina_elizaveta

preprocessors:
  preproc_txx: &prep_txx
    custom_order: True
    regrid:
      target_grid: 0.5x0.5
      lon_offset: 0.25
      lat_offset: 0.25
      scheme: linear    
    extract_shape:
      shapefile: british_columbia.shp
      method: contains
      crop: True
    area_statistics:
      operator: mean
    annual_statistics:
      operator: max
    anomalies:
      period: full
      reference:
        start_year: 1940
        start_month: 1
        start_day: 1
        end_year: 1959
        end_month: 12
        end_day: 31    

  preproc_txx_all: 
    <<: *prep_txx
    clip_timerange:
      timerange: 2011-01-01/2020-12-31

datasets_tasmax: &datasets_tasmax
  - {dataset: TaiESM1, ensemble: r1i1p1f1, grid: gn}

diagnostics:
  xcbox32:
    description: Figure for BC extremes
    variables:
      all:
        short_name: tasmax
        exp: [historical, ssp245]
        start_year: 1940
        end_year: 2030
        project: CMIP6
        mip: day
        preprocessor: preproc_txx_all
        additional_datasets: *datasets_tasmax 
    scripts: null
```

By the looks of it, the second `clip_timerange` didn't work, and the cube has 91 years, although before it was supposed to have 20 (at least worked with `extract_timerange`). Suggestions welcome.
