### ISSUE TITLE
Processing ERA5 (project native6) leads to huge dask graphs

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#2375]
The following very simple recipe leads to lots of dask tasks, which slows down the calculations a lot. This becomes especially bad if additional custom preprocessor steps are used.

```yaml
documentation:
  description: Test
  authors:
    - schlund_manuel
  title: Test.

datasets:
  - {dataset: ERA5, project: native6, type: reanaly, version: v1, tier: 3}

diagnostics:
  test:
    scripts:
      null
    variables:
      ta:
        mip: Amon
```

These are the dask graph sizes after each preprocessing step:

```bash
load
after: 2107

fix_metadata
before: 2107
after: 10363

concatenate
before: 10363
after: 17587

cmor_check_metadata
before: 17587
after: 17587

fix_data
before: 17587
after: 17587

cmor_check_data
before: 17587
after: 17587

add_supplementary_variables
before: 17587
after: 17587

save
before: 17587
```

As you can see, `fix_metadata` and `concatenate` add ~7500 elements to the graph each. @ESMValGroup/technical-lead-development-team
