### ISSUE TITLE
Automatically select a lazy regridding scheme in `regrid` preprocessor function for 2D lat/2D lon grids when possible

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#2405]
Through iris-esmf-regrid and the [generic regridding schemes](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html#horizontal-regridding), it is possible to regrid grids with 2D latitude and 2D longitude coordinates lazily. However, these regridding schemes are not automatically selected and instead the non-lazy ESMPyLinear/ESMPyNearest/ESMPyAreaWeighted built-in schemes are selected. This results in poor computational performance by default.

@schlunma @sloosvel Do you think it would be possible to improve the default so we prefer lazy schemes and automatically select those when possible?

**Comment by sloosvel** [comment]
I'm not sure this is possible because the generic regridding schemes don't work for all models, you can get results such as this one using ESMFAreaWeighted:

![image](https://github.com/ESMValGroup/ESMValCore/assets/45196700/7dcb0c10-440e-43bc-9fae-deac30a5dcca)

**Comment by bouweandela** [comment]
Could you provide some more details on that image, to help me understand the issue?
- What was the source grid or model?
- what was the target grid?
- Which regridding scheme was used?

**Comment by sloosvel** [comment]
It happens to models that have OceanGridFix applied to them. The generated bounds work fine to regrid with the non-lazy regridders, but for some reason when you call the lazy AreaWeighted scheme, this happens. You can check with the recipe below for instance:

```yaml
documentation:
  title: test regrid
  description: |
    Test regrid
  authors:
     - loosveldt-tomas_saskia

datasets:
   - {dataset: FGOALS-g3, ensemble: r1i1p1f1, exp: historical, project: CMIP6, grid: gn, timerange: 1951/1951}


preprocessors:
  pp:
    regrid:
      target_grid: 1.5x1.5
      scheme: 
        reference: esmf_regrid.schemes:ESMFAreaWeighted

diagnostics:
  test_regrid:
    variables:
      tos:
        mip: Omon
        preprocessor: pp
    scripts: null


```
