### ISSUE TITLE
Speed up loading for ACCESS-ESM non-CMOR datasets

### ISSUE THREAD

**Issue by rhaegar325** [ESMValGroup/ESMValCore#2487]
Hi, Develop team, 
in the last few month we developed a cmoriser for ACCESS-ESM raw data in ESMValCore. However, due to the different way to store the data(typically cmored data was store by single variable in all time-range in a file, ACCESS-ESM data was stored by one timestamp with all variables in one file), if we still use the default way in esmvalcore to load ACCESS-ESM data, that will cause a huge time and memory cost. so I was wondering if we could build a load method for ACCESS-esm raw data that will be super helpful, won't need to be conplex, just a filter to select file within time-range which specified in recipe would be good. 

I open this issue to see if anyone have good idea about how to do that. I am willing to implement myself, just need to know which way was the best that both of us will accept.

**Comment by rbeucher** [comment]
Hi @bouweandela, @valeriupredoi,

We are encountering an issue with the output of the ACCESS-ESM model, specifically with the atmospheric data. The data is stored as follows:

```bash
./atm/netCDF/:
HI-CN-05.pa-185001_mon.nc
HI-CN-05.pa-185002_mon.nc
HI-CN-05.pa-185003_mon.nc
HI-CN-05.pa-185004_mon.nc
HI-CN-05.pa-185005_mon.nc
HI-CN-05.pa-185006_mon.nc
HI-CN-05.pa-185007_mon.nc
HI-CN-05.pa-185008_mon.nc
HI-CN-05.pa-185009_mon.nc
HI-CN-05.pa-185010_mon.nc
```

All monthly variables are stored in a single netCDF file.

Currently, our `config-developer.yml` is configured as follows:

```yml
ACCESS:
  cmor_strict: false
  input_dir:
    default:
      - '{dataset}/{sub_dataset}/{exp}/{modeling_realm}/netCDF'
  input_file:
      default: '{sub_dataset}.{special_attr}-*.nc'
  output_file: '{project}_{dataset}_{mip}_{exp}_{institute}_{sub_dataset}_{special_attr}_{short_name}'
  cmor_type: 'CMIP6'
  cmor_default_table_prefix: 'CMIP6_'
```

This configuration results in ESMValCore analyzing all files and variables, which consumes excessive time and resources.

I have suggested the following to @rhaegar325:

1. **Modify the `input_file/default` to include a time facet**. This change should prevent loading more data than necessary when working within a constrained time range.
2. **Utilize the `timerange` facet in the `input_file` name**. We could implement the approach described [here](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/overview.html#time-ranges).
3. **Leverage IRIS constrained loading capabilities**. Details are available [here](https://scitools-iris.readthedocs.io/en/latest/userguide/loading_iris_cubes.html#constrained-loading). This could potentially speed up the process.

Given that all variables are stored in a single file, we are aware that this setup is not optimal. However, we currently have no alternative.

Any advice would be greatly welcome!

Thanks,
R
