### ISSUE TITLE
Poor performance of lazy `mask_landsea` preprocessor

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#2514]
**Describe the bug**

The preprocessor `mask_landsea` is performing poorly with high-res data. When running the following recipe with dask distributed, the task execution basically freezes. Removing the masking preprocessor fixes this issue.

Example recipe:

```yml
documentation:
  title: High-res evaluation
  description: Simple evaluation of high-res model output.
  authors:
    - schlund_manuel

preprocessors:
  nh_land_mean_annual_cycle:
    mask_landsea:
      mask_out: sea
    extract_region:
      start_latitude: 30.0
      end_latitude: 90.0
      start_longitude: 0.0
      end_longitude: 360.0
    area_statistics:
      operator: mean
    monthly_statistics:
      operator: mean
    climate_statistics:
      operator: mean
      period: month

diagnostics:
  annual_cycle:
    variables:
      tas:
        mip: day
        project: CMIP6
        exp: highresSST-present
        preprocessor: nh_land_mean_annual_cycle
        timerange: 1950/1960
    scripts: null

datasets:
  - {dataset: NICAM16-9S, ensemble: r1i1p1f1, grid: gr}
```

I could trace that to the usage of `da` instead `np` [here](https://github.com/ESMValGroup/ESMValCore/blob/412ac53727e8e545d78bb6f98621e6fef9149911/esmvalcore/preprocessor/_mask.py#L288). In addition, the [broadcasting](https://github.com/ESMValGroup/ESMValCore/blob/412ac53727e8e545d78bb6f98621e6fef9149911/esmvalcore/preprocessor/_mask.py#L317) actually never happens since the function's return value is not used.

I will provide a fix for that.
