### ISSUE TITLE
Readthedocs builds still use Mambaforge

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#2557]
We retired Mambaforge in #2556 - everywhere in ESMValCore, apart from the RTD configuration, since at the mo I don't think they support a Miniforge3 variant, and going back to Miniconda is just silly, see https://github.com/readthedocs/readthedocs.org/issues/11690

We may have to switch to Miniconda while they are working on it, it appears it'll take a hwile, according to Manuel https://github.com/readthedocs/readthedocs.org/issues/11690#issuecomment-2417106815

We reverted to miniconda-latest in #2562  and, as @bouweandela found out, that configuration is taking significantly less to build the environment (since mamba is the default solver for miniconda), so, we may want to keep it permanently; if we decide to test with Miniforge3, when it becomes available, the previous commands in the readthedocs.yml file were useful:

```yaml
build:
  os: ubuntu-22.04
  tools:
    # replace when miniforge3 when available
    # DO NOT use mambaforge-*; that is currently sunsetted
    python: "miniconda-latest"  # need miniforge3
  jobs:
    # Put these back when we have Miniforge3 from RTD
    # pre_create_environment:
    #   # update mamba just in case
    #   - mamba update --yes --quiet --name=base mamba 'zstd=1.5.2'
    #   - mamba --version
    #   - mamba list --name=base
    post_create_environment:
      # - conda run -n ${CONDA_DEFAULT_ENV} mamba list
      # use conda run executable wrapper to have all env variables
      # - conda run -n ${CONDA_DEFAULT_ENV} mamba --version
      - conda run -n ${CONDA_DEFAULT_ENV} pip install . --no-deps
```
