### ISSUE TITLE
Some tests fail if custom Dask configuration is used

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#2623]
With the file
```yaml
 $ cat ~/.config/esmvaltool/dask.yaml 
dask:
  use: test
  profiles:
    test:
      cluster:
        type: distributed.LocalCluster
        n_workers: 4
        threads_per_worker: 1
        memory_limit: 2GiB
```
Some tests from `tests/unit/config/test_dask.py` fail for me with the following error message:
```
FAILED tests/unit/config/test_dask.py::test_get_no_distributed_client - AssertionError: assert <Client: 'tcp://127.0.0.1:41011' processes=4 threads=4, memory=8.00 GiB> is None
FAILED tests/unit/config/test_dask.py::test_get_distributed_client_empty_dask_file - OSError: Timed out trying to connect to tcp://127.0.0.1:41011 after 30 s
```

@schlunma Could you have a look? I expect there may be a need to `monkeypatch` the CFG object before running the tests.
