### ISSUE TITLE
Adding supplementary variables from a different project

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValCore#2745]
I am trying to calculate area averaged means for the `tos` variable from the TerraFIRMA project simulations available as CMOR-ized data on JASMIN (/gws/nopw/j04/terrafirma/TerraFIRMA). I created the appropriate entry for a new project in the config file and am able to generally access and preprocess data from these simulations. However, when I need to use the `areacello` file, I run into a problem. This is because the TerraFIRMA simulations use the areacello file from `UKESM1-0-LL`.  File location is at : 

`/badc/cmip6/data/CMIP6/CMIP/MOHC/UKESM1-0-LL/piControl/r1i1p1f2/Ofx/areacello/`

I created a recipe to do this but the supplementary variable inclusion does not recognize the different project (`CMIP6`) or dataset (`UKESM1-0-LL`).

The recipe is as follows: 

```
# ESMValTool
# recipe_tf_tos_process.yml
#
---
documentation:
  description: |
    Example recipe that tests processing tos variable for TF overshoot and hist simulations.

  title: Recipe that runs an example diagnostic written in Python.

  authors:
    - swaminathan_ranjini

  maintainer:
    - swaminathan_ranjini

  references:
    - ukesm

  projects:
    - ukesm

preprocessors:
  calculate_area_averages:
    area_statistics:
      operator: mean

diagnostics:
  calculate_aa:
    description: Calculate tos area average.
    variables:
      tos_mean:
        short_name: tos        
        timerange: '1975/2014'        
        supplementary_variables:
          - short_name: areacello
            mip: Ofx
            project: CMIP6
            dataset: UKESM1-0-LL
            ensemble: r1i1p1f2
            exp: piControl

        preprocessor: calculate_area_averages
    additional_datasets: 
      - {project: TerraFIRMA, dataset: UKESM1-2, institute: MOHC, mip: Omon, grid: gn, exp: esm-hist, ensemble: r1i1p1f1}
    scripts: null
```
@valeriupredoi - can you let me know if this is ok to do? I have created a `config-developer` file for use with the TerraFIRMA simulations in `/gws/nopw/j04/terrafirma/esmvaltool`.
