### ISSUE TITLE
area_weighted regridding fails on several observational datasets

### ISSUE THREAD

**Issue by bascrezee** [ESMValGroup/ESMValCore#289]
The preprocessor function `regrid` with argument `scheme = 'area_weighted'` fails on several observational datasets. The error thrown is:
```
File "/iris/experimental/regrid.py", line 680, in regrid_area_weighted_rectilinear_src_and_grid
    raise ValueError("The horizontal grid coordinates of both the source "
ValueError: The horizontal grid coordinates of both the source and grid cubes must have contiguous bounds.
```

```
# Version info
In [2]: iris.__version__                                                                                            
Out[2]: '2.2.1dev0'
```

Please find below the recipe, including one dataset for which everything works fine. This bug is possibly related to: https://github.com/SciTools/iris/issues/2061

Recipe: 
```
# ESMValTool
---
documentation:
  description: |
    Test recipe recipe_bug_area_weighted.yml 

  authors:
    - crezee_bas


################################################
# Define some default parameters using anchors #
################################################
timeperiod: &timeperiod
  start_year: 2009
  end_year: 2010

################################################
################################################
################################################

datasets:
#
### This dataset works fine:
  - { dataset: CDS-SATELLITE-SOIL-MOISTURE, type: sat, project: OBS, mip: Lmon, version: COMBINED-TCDR-v201812.0.0, tier: 3, << : *timeperiod }
#
### The following three datasets suffer from the bug:
  - { dataset: cds-era5-land-monthly, type: reanaly, project: OBS, mip: Lmon, version: 1, tier: 3, <<: *timeperiod }
  - {dataset: eraintland, type: reanaly, project: OBS6, mip: E6hr, version: 1, tier: 3, frequency: 6hr, <<: *timeperiod }
  - { dataset: cds-era5-monthly, type: reanaly, project: OBS, mip: Lmon, version: 1, tier: 3, <<: *timeperiod }
  - { dataset: CDS-UERRA, type: reanaly, project: OBS6, mip: E6hr, version: UERRA-HARMONIE, tier: 3, frequency: 6hr, << : *timeperiod }

preprocessors:
  pp_regrid:
    regrid:
      target_grid: 1x1
      scheme: area_weighted   # 'nearest' works fine for all datasets above

diagnostics:
  mapplots:
    description: mapplots
    variables:
      sm:
        preprocessor: pp_regrid
        mip: Lmon
    scripts:
      null
```

I will do my best to look further into this, but any help is greatly appreciated!
