### ISSUE TITLE
Consider using the intake library

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#31]
It could be interesting to replace our home grown esmvaltool/_data_finder.py module by the much more advanced [`intake`](https://intake.readthedocs.io/en/latest/index.html) library and the associated [`intake-iris`](https://github.com/informatics-lab/intake-iris) plugin.

**Comment by bouweandela** [comment]
Interesting project, but it doesn't support iris and custom DRS at the moment, https://intake-esm.readthedocs.io/en/latest/index.html

**Comment by bouweandela** [comment]
Example using intake_iris:
```python
import intake
cat = intake.Catalog("catalog.yaml")
source = cat['CMIP5'].get(short_name='ta', mip='Amon', dataset='MPI-ESM-MR', exp='historical', ensemble='r1i1p1')
cubes = source.to_dask()
```
where catalog.yaml looks like
```yaml
metadata:
  version: 1

sources:

  CMIP5:
    description: ''
    driver: intake_iris.NetCDFSource
    args:
      urlpath: '/home/bandela/esmvaltool_input/{{short_name}}_{{mip}}_{{dataset}}_{{exp}}_{{ensemble}}*.nc'
    parameters:
      dataset:
        description: Dataset
        type: str
      short_name:
        description: Short name
        type: str
      mip:
        description: MIP table
        type: str
      exp:
        description: Experiment
        type: str
      ensemble:
        description: Ensemble
        type: str
```
I'm not sure if this is the right way to use it though. [Structured file paths](https://intake.readthedocs.io/en/latest/making-plugins.html?highlight=path_as_pattern#structured-file-paths) also look useful, but are not supported by the intake_iris plugin.
