### ISSUE TITLE
How to regrid fx files

### ISSUE THREAD

**Issue by npgillett** [ESMValGroup/ESMValCore#43]
I would like to regrid an fx file - `sftlf `- onto a 5x5 grid. I need this as input to an existing python package which is expecting tas, tos, siconc and sftlf in NetCDF files on a 5x5 grid, to produce masked and blended GMST. I can regrid `tas`, `tos` and `siconc` onto a 5x5 grid using the `regrid` preprocessor, by adding this to the recipe like this:

```
preprocessors:

  regrid_5_5:
    regrid:
      target_grid: 5x5
      scheme: linear

diagnostics:

  fig_test_attribute:
    description: Test of masked and blended surface temperature.
    variables:
      tas:
        preprocessor: regrid_5_5   
        mip: Amon
        field: T2Ms
        project: CMIP6
        exp: historical
        grid: gr
        start_year: 1850
        end_year: 2014
    additional_datasets:
      - {dataset: CNRM-CM6-1, ensemble: r1i1p1f2}
```

This works OK. But if I try to do the same for sftlf by adding this:
```
      sftlf:
        preprocessor: regrid_5_5
        mip: fx
        field: F2Ms
        project: CMIP6
        exp: historical
        grid: gr

```
Then I get this:
`esmvaltool._recipe_checks.RecipeError: Missing keys {'end_year', 'start_year'} from variable sftlf in diagnostic fig_test_attribute`
and the recipe does not run.

If I add a dummy start year and end year, then I get:
 ```
   raise RecipeError("No input files found for variable {}".format(var))
esmvaltool._recipe_checks.RecipeError: No input files found for variable {'preprocessor': 'regrid_5_5', 'mip': 'fx', 'field': 'F2Ms', 'project': 'CMIP6', 'exp': 'historical', 'grid': 'gr', 'start_year': 1850, 'end_year': 2014, 'variable_group': 'sftlf', 'short_name': 'sftlf', 'diagnostic': 'fig_test_attribute', 'dataset': 'CNRM-CM6-1', 'ensemble': 'r1i1p1f2', 'recipe_dataset_index': 0, 'cmor_table': 'CMIP6', 'institute': ['CNRM-CERFACS'], 'standard_name': 'land_area_fraction', 'long_name': 'Land Area Fraction', 'units': '%', 'modeling_realm': ['atmos'], 'frequency': 'fx', 'filename': '/scratch/b/b380746/esmvaltool_output/test_attribute_20190307_231334/preproc/fig_test_attribute/sftlf/CMIP6_CNRM-CM6-1_fx_historical_r1i1p1f2_F2Ms_sftlf_1850-2014.nc'}
```
and again the recipe doesn't run.

I thought that specifying the field `F2Ms` should mean that years are not required, but this doesn't seem to be implemented. I don't actually want to mask the `tas`, `tos`, or `siconc` with `sftlf` at this point, I just want the regridded sftlf file. (The masking a blending code for example uses tas over sea ice, so masking tas with sftlf would not be helpful).

Thanks very much!
