### ISSUE TITLE
Irregular regridding fails for specific dataset

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#480]
**Describe the bug**
For historical `tos` of `MRI-CGCM3`, irregular regridding gives an empty field (completely filled with 0s). The original data is fine.

**Recipe**

```yml
preprocessors:
  regrid:
    regrid:
      target_grid: 2x2
      scheme: linear

diagnostics:
  diag_x_zhai:
    variables:
      tos:
        preprocessor: regrid
        exp: historical
        ensemble: r1i1p1
        project: CMIP5
        mip: Omon
        start_year: 1980
        end_year: 2004
        reference_dataset: ''
    additional_datasets:
       - {dataset: MRI-CGCM3}
    scripts: null
```
