### ISSUE TITLE
`extract_month` not functioning properly

### ISSUE THREAD

**Issue by bascrezee** [ESMValGroup/ESMValCore#481]
**Describe the bug**
The preprocessor `extract_month` does not work when the input cube does not yet have the auxiliary coordinate `month_number`. It needs to be added first if it is not there yet.

Example recipe:
```
CMIP5_landcover: &CMIP5_landcover
  additional_datasets:
    - {dataset: MPI-ESM-LR, project: CMIP5, ensemble: r1i1p1}

preprocessors:
  pp_cmip:
    custom_order: true
    regrid:
      target_grid: 2x2
      scheme: linear
    extract_month: # This preprocessor returns None (bug)
      month: 7
    climate_statistics:
      operator: mean

diagnostics:
  albedolandcover_cmip5:
    description: test
    variables:
      treeFrac: &variable_settings_cmip5
        preprocessor: pp_cmip
        mip: Lmon
        exp: historical
        start_year: 2000
        end_year: 2004
        <<: *CMIP5_landcover
    scripts:
      albedolandcover:
        script: landcover/jumpintoipython.py
```
