### ISSUE TITLE
New preprocessor mask_multimodel

### ISSUE THREAD

**Issue by bascrezee** [ESMValGroup/ESMValCore#487]
**Is your feature request related to a problem? Please describe.**
I want to propagate the mask over several datasets such that when an element is masked in one dataset, it is also masked in all other datasets.

**Would you be able to help out?**
Yes, working on it. Initially I thought `mask_fillvalues` would do the job, but it doesn't. Also Github kindly points me to other issues, and just now I realize this has been discussed before here https://github.com/ESMValGroup/ESMValCore/issues/116

**Comment by mattiarighi** [comment]
Can you be more specific on why `mask_fillvalues` doesn't do what you need.
From the feature request it looks like this is exactly what `mask_fillvalues` was designed for.

@valeriupredoi

**Comment by bascrezee** [comment]
Yes, let me try to clarify.

```
datasets:
  - {dataset: cds-era5-monthly, type: reanaly, project: OBS, mip: Lmon,
     version: 1, tier: 3, start_year: 2008, end_year: 2010}
  - {dataset: CDS-SATELLITE-SOIL-MOISTURE, type: sat, project: OBS, mip: Lmon,
     version: COMBINED-TCDR-v201812.0.0, tier: 3, start_year: 2008, end_year: 2010}

preprocessors:
  test_b:
    regrid:
      target_grid: 0.25x0.25
      scheme: nearest
    mask_fillvalues:
      threshold_fraction: 0.00    # keep all missing values
      min_value: -1e+20           # small enough not to alter the data
```

In my diagnostic script:
```
def _get_cubelist(cfg):
    input_data = cfg['input_data'].values()
    grouped_input_data = group_metadata(
        input_data, 'dataset', sort='dataset')
    cubes = []
    for datasetname in grouped_input_data.keys():
        cubes.append(iris.load_cube(grouped_input_data[datasetname][0]['filename']))
    return iris.cube.CubeList(cubes)


def main(cfg):
    """Calculate linear regression between albedo and xxfrac.

    Arguments:
    ---------
        cfg - nested dictionary of metadata
    """
    cubelist = _get_cubelist(cfg)
    assert(np.array_equal(cubelist[0].data.mask, cubelist[1].data.mask))
```

Executing raises `AssertionError`

**Comment by mattiarighi** [comment]
Maybe we should try to extend or adapt `mask_fillvalues` rather than create a new preprocessor.
@valeriupredoi any suggestion?

**Comment by bascrezee** [comment]
Yes, I would be in favour of that as well. There is another tiny bug in mask_fillvalues as well, let's fix that first (working on it).

**Comment by valeriupredoi** [comment]
@bascrezee can you post the output of `np.where((cubelist[0].data.mask ^ cubelist[1].data.mask) is True)` pliz :beer:

**Comment by valeriupredoi** [comment]
there is no actual reason why to implement a new preproc func for this - it should work as it is now for exactly this purpose, unless, of course, there is a bug that I have not seen so far (totally possible)

**Comment by valeriupredoi** [comment]
also I think I know where your assertion error comes from - if you have time axes with different dimesnions, then the assertion error will come up - try `assert(np.array_equal(cubelist[0][0].data.mask, cubelist[1][0].data.mask))`

**Comment by bascrezee** [comment]
Thanks for the super fast support guys. Have to leave now, I will look further into this tomorrow.

**Comment by bascrezee** [comment]
```
    # Check if the masks are exactly equal
    a = cubelist[0].data.mask
    b = cubelist[1].data.mask

    print("Check 1 as requested by V: ")
    print(np.where((a ^ b) is True))
    print("Check 2: ")
    print((a==b).all())
    print("Check 3: ")
    print(np.array_equal(a,b))
```

```
Check 1 as requested by V:
(array([], dtype=int64),)
Check 2:
False
Check 3:
False
```

So the arrays are not equal in my use case, and indeed I could trace it to a slightly differing time axis (1 day shifted) as suggested by @valeriupredoi.

**Comment by valeriupredoi** [comment]
Phew, so our jood old method is still accurate then :beer

**Comment by valeriupredoi** [comment]
Sorry, pressed the wrong button on my phone. Cheers, so the method is still accurate phew :beer:

**Comment by valeriupredoi** [comment]
can close this @bascrezee no? :beer:

**Comment by schlunma** [comment]
I tried to implement the feature that @bascrezee describes in this issue (apply a common mask to all datasets) with this recipe (also following [this](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html?highlight=mask#common-mask-for-multiple-models) section of the documentation).

```yaml
---
documentation:
  description: |
    test.

  authors:
    - schlund_manuel

  maintainer:
    - schlund_manuel

  references: []

  projects:
    - crescendo


preprocessors:

  preproc:
    regrid:
      target_grid: 5x5
      scheme: nearest
    mask_fillvalues:
      threshold_fraction: 0.0
      min_value: -1e20


diagnostics:

  diag_test:
    variables:
      tas:
        project: CMIP6
        exp: historical
        preprocessor: preproc
        mip: Amon
        start_year: 2005
        end_year: 2005
        var_type: feature
        additional_datasets:
          - {dataset: HadCRUT4, short_name: tas, project: OBS, type: ground, version: '1', tier: 2}
          - {dataset: BCC-CSM2-MR, ensemble: r1i1p1f1, grid: gn}
    scripts:
      null
```

However, the preprocessed files do not have the same mask:

**GitHub does not let me insert a png right now, I will upload it tomorrow**

Can someone tell what the correct settings for `mask_fillvalues` are to simply get a common mask? I also vote strongly for adding the suggested preprocessor `mask_multimodel`. To be honest, I do not completely understand the different parameters used in `mask_fillvalues`, so a simple wrapper for this might be helpful.

**Comment by schlunma** [comment]
I tried to implement the feature that @bascrezee describes in this issue (apply a common mask to all datasets) with this recipe (also following [this](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html?highlight=mask#common-mask-for-multiple-models) section of the documentation).

```yaml
---
documentation:
  description: |
    test.

  authors:
    - schlund_manuel

  maintainer:
    - schlund_manuel

  references: []

  projects:
    - crescendo


preprocessors:

  preproc:
    regrid:
      target_grid: 5x5
      scheme: nearest
    mask_fillvalues:
      threshold_fraction: 0.0
      min_value: -1e20


diagnostics:

  diag_test:
    variables:
      tas:
        project: CMIP6
        exp: historical
        preprocessor: preproc
        mip: Amon
        start_year: 2005
        end_year: 2005
        var_type: feature
        additional_datasets:
          - {dataset: HadCRUT4, short_name: tas, project: OBS, type: ground, version: '1', tier: 2}
          - {dataset: BCC-CSM2-MR, ensemble: r1i1p1f1, grid: gn}
    scripts:
      null
```

However, the preprocessed files do not have the same mask:

**GitHub does not let me insert a png right now, I will upload it tomorrow**

Can someone tell what the correct settings for `mask_fillvalues` are to simply get a common mask? I also vote strongly for adding the suggested preprocessor `mask_multimodel`. To be honest, I do not completely understand the different parameters used in `mask_fillvalues`, so a simple wrapper for this might be helpful.

**Comment by schlunma** [comment]
I tried to implement the feature that @bascrezee describes in this issue (apply a common mask to all datasets) with this recipe (also following [this](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html?highlight=mask#common-mask-for-multiple-models) section of the documentation).

```yaml
---
documentation:
  description: |
    test.

  authors:
    - schlund_manuel

  maintainer:
    - schlund_manuel

  references: []

  projects:
    - crescendo


preprocessors:

  preproc:
    regrid:
      target_grid: 5x5
      scheme: nearest
    mask_fillvalues:
      threshold_fraction: 0.0
      min_value: -1e20


diagnostics:

  diag_test:
    variables:
      tas:
        project: CMIP6
        exp: historical
        preprocessor: preproc
        mip: Amon
        start_year: 2005
        end_year: 2005
        var_type: feature
        additional_datasets:
          - {dataset: HadCRUT4, short_name: tas, project: OBS, type: ground, version: '1', tier: 2}
          - {dataset: BCC-CSM2-MR, ensemble: r1i1p1f1, grid: gn}
    scripts:
      null
```

However, the preprocessed files do not have the same mask:

**GitHub does not let me insert a png right now, I will upload it tomorrow**

Can someone tell what the correct settings for `mask_fillvalues` are to simply get a common mask? I also vote strongly for adding the suggested preprocessor `mask_multimodel`. To be honest, I do not completely understand the different parameters used in `mask_fillvalues`, so a simple wrapper for this might be helpful.
