### ISSUE TITLE
Support per dataset DRS

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#494]
Now that we have support for reading in the ERA5 dataset in it's native format through the `native6` project (https://github.com/ESMValGroup/ESMValCore/issues/447), it would be good to add support for a per dataset DRS, so other datasets (which will typically come with their own DRS) can also be supported using the `native6` project.

**Comment by valeriupredoi** [comment]
`config-developer.yml` or you thinking something fancier so we don't overcrowd the file? :beer:

**Comment by bouweandela** [comment]
Yes, just in config-developer.yml

**Comment by bouweandela** [comment]
Related to  #641

**Comment by bsolino** [comment]
I have made this suggestion of how the config_developer file could look inhttps://github.com/ESMValGroup/ESMValCore/pull/970#issuecomment-825805649, but I think it could be relevant to this discussion:

```
native6:
  default:
    input_dir:
      default: 'Tier{tier}/{dataset}/{latestversion}/{frequency}/{short_name}'
      BSC: '{project}/{dataset}_{version}/{area}_{frequency}_{grid}'
      RCAST: '...'
    input_file:
      default: '*.nc'
      BSC: '*.nc'
      RCAST: '*.nc'
  ICON:
    input_dir:
      default: '{model_version}_{model_component}_{experiment}_{grid}_{id}'
    input_file:
      default: '{model_version}_{model_component}_{experiment}_{grid}_{id}_{var_type}*.nc'
  EMAC:
    ...
```
