### ISSUE TITLE
Comparing several single model ensembles

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#52]
Hi all,

two very common things that users will want to do in ESMValTool are:

1. Compare single model ensemble means.
  For instance, I have a HadGEM2-ES 4 member ensemble and UKESM 12 member ensemble. I want to make some time series plots showing the time development of the two single-model ensemble means. 
  How do I do that?  Is there a way to use the multi_model_statistics preprocessor so that it only compares single models? Or perhaps we need a single_model_ensemble_statistics preprocessor? 

2. Calculate the differences between two specific time periods in the preprocessor stage.
  For instance, I want to look at  average surface temperature in the years 1975-2000  minus the average surface temperature between 1875-1900. 
  I don't know of a way to do this in the preprocessor, it seems to be such a common job that it would be great to get it as a preprocessor instead of in the diagnostic stage.

Any ideas?

Lee

**Comment by sloosvel** [comment]
@jvegasbsc and I have been looking into creating a preprocessing function to able to compute ensemble means. I have a draft in a branch that groups the input products and then calls the multi_model_statistics function per grouped dataset. But then I found this issue so maybe it's better to continue here the discussion.

**Comment by Peter9192** [comment]
Any new insights on this? @sloosvel have you abandoned that branch or do you think it's still a viable option?

**Comment by sloosvel** [comment]
It must be quite outdated, but I think that with #637 it will be easier to implement.

**Comment by Peter9192** [comment]
So you'd suggest starting from scratch, or is there anything that can be re-used from your branch?

If starting from scratch, and considering that 

>  the ensemble statistics should not be performed after regridding (while the multimodel statistics do)

would it make sense to write a new function, rather than calling multimodel stats under the hood? I suppose doing multimodel stats on consistent (same model/grid/etc) datasets could be more straightforward and maybe even lazy?

**Comment by Peter9192** [comment]
Thanks for all the info Bouwe! My use case would be to combine both ensemble means and multimodel statistics, to prevent models with many ensemble member getting excessive weight in the MM stats. 
Like you say, this can be achieved with the current functionality by doing the multi model stats in a Python diagnostic, but a separate preprocessor function would be nicer. An alternative solution for this use case would be for multimodel stats to support weights.

**Comment by sloosvel** [comment]
>Having a dedicated ensemble_statistics preprocessor would probably be nicer than the current solution

I think that this combined with the groupby option is the most convenient solution. Because at some point I tried to extend the multi_model function and it ended up being very messy.

**Comment by bettina-gier** [comment]
Just adding onto this discussion, I talked with members from the 4C project yesterday who were asking about averaging observational datasets in the esmvaltool. Considering there are currently different "projects" for observations like obs4mips, OBS, OBS6, it could be needed to add some kind of optional tag or group to datasets in the recipe, which could then also be the input for the "groupby" option Bouwe proposed above, e.g. hijacking the recipe idea above

```
preprocessors:
  statistics:
    multi_model_statistics:
      span: overlap
      statistics: [mean, median]
      groupby: [obs_avg, CMIP5]

diagnostics:
  diagnostic1:
    variables:
      ta:
        mip: Amon
        project: CMIP5
        preprocessor: statistics
        start_year: 2000
        end_year: 2002
        exp: historical
        additional_datasets:
          - {dataset: CRU, project: OBS, tag: obs_avg, ...}
          - {dataset: ERA-Interim, project: OBS6, tag: obs_avg, ...}
          - {dataset: CanESM2, ensemble: r(1:5)i(1:2)p1}
          - {dataset: MPI-ESM-LR, ensemble: r(1:5)i1p1}
          - {dataset: bcc-csm1-1, ensemble: r(1:5)i1p1}
          - {dataset: GFDL-ESM2G, ensemble: r1i1p(1:5)}      
```

Additionally they were asking if there is a possibility for giving weights to observations if this mean was computed, say 70% weight for dataset 1 and only 30% for dataset 2. Is this currently possible with the preprocessor and if not, would we want it to be? Or should this rather be given as parameters to diagnostics, potentially introducing a class of "preprocessor diagnostics" between preprocessor and diagnostics for more involved computations which can then be forwarded to "normal" diagnostics using the ancestors tag?

**Comment by Peter9192** [comment]
> potentially introducing a class of "preprocessor diagnostics"

This is something I've been thinking about as well in the context of https://github.com/ESMValGroup/ESMValTool/issues/1640. Several different weighting methods are developed in EUCP, and we're considering to add several more of them to ESMValTool. I guess it's a natural way to start implementing them as diagnostics and maybe, once that converges to some sort of common interface, we could consider porting them to the preprocessor. Does that make sense?

**Comment by stefsmeets** [comment]
> 
> 
> Just adding onto this discussion, I talked with members from the 4C project yesterday who were asking about averaging observational datasets in the esmvaltool. Considering there are currently different "projects" for observations like obs4mips, OBS, OBS6, it could be needed to add some kind of optional tag or group to datasets in the recipe, which could then also be the input for the "groupby" option Bouwe proposed above, e.g. hijacking the recipe idea above


In #673 we made some progress to make this possible. Internally we added support for grouping data to do ensemble statistics, but in principle, anything can be grouped, as long as it is defined in the dataset attributes. This functionality can be exposed quite easily.

What you would then do would be something like:

```yaml
preprocessors:
  statistics:
    multi_model_statistics:
      span: overlap
      statistics: [mean, median]
      groupby: [tag, dataset]
```
