### ISSUE TITLE
Fallback option for weighting_landsea_fraction in case specific models don't have fx data

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#547]
Simply put:

```
 preproc_weighting:
    weighting_landsea_fraction:
      fallback_fx_dataset: UKESM1-0-LL 
      area_type: land
```

where `fallback_fx_dataset` to be used for each model that doesn't have `sftlf/of` data. This was initially suggested by @ChrisJones-MOHC and is a viable option if not a bit scientifically loose but then again, the fx data doesn't change too much from model to model anyway.
@schlunma do you have time to plug it in? If not, no problemo, I can do it :beer:
