### ISSUE TITLE
Simplify default DRS for native6 project

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#641]
Because the data used with the `native6` project can have any filename, it might be nice to make the default DRS
```
  input_dir:
    default: '{dataset}/{latestversion}/{frequency}/{short_name}'
  input_file:
    default: '*.nc'
```
because this would allow using the filenames that the data comes with without renaming. You could just download the data, put it in the right directory and be done. It would also avoid the issue reported here: https://github.com/ESMValGroup/ESMValTool/pull/1644#issue-413480838.
