### ISSUE TITLE
Landsea mask not working when model has sftof but not sftlf

### ISSUE THREAD

**Issue by bettina-gier** [ESMValGroup/ESMValCore#658]
When a model has stfof but not sftlf fx files, in a landsea mask the fx_variables are shown as 

```
'fx_variables': {'sftlf': [], 'sftof': '/work/ik1017/CMIP6/data/CMIP6/CMIP/NCC/NorESM2-MM/historical/r1i1p1f1/Ofx/sftof/gn/v20191108/sftof_Ofx_NorESM2-MM_historical_r1i1p1f1_gn.nc'}
```
and in the loop at preprocessor _mask.py line 134ff

```
    fx_files = fx_variables.values()
    if any(fx_files) and not always_use_ne_mask:
        fx_cubes = {}
        for fx_file in fx_files:
            fxfile_members = os.path.basename(fx_file).split('_')
```
it fails at os.path.basename(fx_file)
```

  File "/mnt/lustre02/work/bd0854/b309137/v2_okt2019/ESMValCore/esmvalcore/preprocessor/_mask.py", line 141, in mask_landsea
    fxfile_members = os.path.basename(fx_file).split('_')
  File "/work/bd0854/b309137/my_anaconda/envs/ipccar6/lib/python3.7/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not list
"""
```

Seems it's trying to feed an empty list to os.basename

Adding
```
        for fx_file in fx_files:
            if not fx_file:
                continue
```
in line 138 of _mask.py solved the issue for me, but I don't know if this is the best way as it may occur elsewhere fx files are needed.

Test recipe:

```
preprocessors:

  landmask:
    mask_landsea:
      mask_out: sea

diagnostics:

  test:
    description: testing landmask!
    variables:
      nbp:
        preprocessor: landmask
        project: CMIP6
        ensemble: r1i1p1f1
        field: T2Ms
        exp: historical
        mip: Lmon
        start_year: 1850
        end_year: 2014
        additional_datasets:
          - {dataset: NorESM2-MM, grid: gn, institute: NCC}
    scripts:
      null
```
Debug log:
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/4702685/main_log_debug.txt)
