### ISSUE TITLE
Anomaly calculation for OBS got broken early march. 

### ISSUE THREAD

**Issue by bascrezee** [ESMValGroup/ESMValCore#710]
**Describe the bug**
Unfortunately, it seems like none of the tests has flagged (something to look into later I would say!). But for several observational datasets the calculation of anomalies goes wrong with non-physical values coming out of the preprocessor. I could track down the problems to 3-4 March 2020. With everything working fine on the 3rd of March (`git checkout 'master@{2020-03-03}'`) and wrong results from 4 March onwards (`git checkout 'master@{2020-03-04}'`). To create the plots and run the recipe, one needs a specific ESMValTool branch: `git checkout C3S_511_MPQB`. But reproducing it and simply inspecting NetCDF output files would work as well of course. Since the changes in the `anomalies`  preprocessor were authored by @jvegasbsc my hope is that he can solve this issue. It would be a good additional check if someone can reproduce the error (@hb326 @BenMGeo or @mattiarighi). The error also occurred for `ERA5`, a dataset that is more widely used. Tagging @hirschim just to keep you updated.

Fine: 
![lineplot_sm_2015-2018_GOOD](https://user-images.githubusercontent.com/27730548/87287705-b83b8d00-c4fa-11ea-8eda-466edc42f436.png)
_Generated using Copernicus Climate Change Service information 2020_

Wrong: 
![lineplot_sm_2015-2018_WRONG](https://user-images.githubusercontent.com/27730548/87287719-bbcf1400-c4fa-11ea-89d2-49e13ac733f1.png)
_Generated using Copernicus Climate Change Service information 2020_

Excerpt from the differences of `ESMValCore`  between 3rd and 4th of March 2020: 
```
diff --git a/esmvalcore/preprocessor/_time.py b/esmvalcore/preprocessor/_time.py
index 1e29395e3..c1cf2071b 100644
--- a/esmvalcore/preprocessor/_time.py
+++ b/esmvalcore/preprocessor/_time.py
@@ -462,16 +462,15 @@ def anomalies(cube, period, reference):
     cube_time = cube.coord('time')
     ref = {}
     for ref_slice in reference.slices_over(ref_coord):
-        ref[ref_slice.coord(ref_coord).points[0]] = da.ravel(
-            ref_slice.core_data())
+        ref[ref_slice.coord(ref_coord).points[0]] = ref_slice.core_data()
+
     cube_coord_dim = cube.coord_dims(cube_coord)[0]
+    slicer = [slice(None)] * len(data.shape)
+    new_data = []
     for i in range(cube_time.shape[0]):
-        time = cube_time.points[i]
-        indexes = cube_time.points == time
-        indexes = iris.util.broadcast_to_shape(indexes, data.shape,
-                                               (cube_coord_dim, ))
-        data[indexes] = data[indexes] - ref[cube_coord.points[i]]
-
+        slicer[cube_coord_dim] = i
+        new_data.append(data[tuple(slicer)] - ref[cube_coord.points[i]])
+    data = da.stack(new_data, axis=cube_coord_dim)
     cube = cube.copy(data)
     cube.remove_coord(cube_coord)
     return cube

commit f61cc0e946dd4cd1de02fb738046f5273db16025
Author: Javier Vegas <javier.vegas@bsc.es>
Date:   Tue Jan 21 16:31:42 2020 +0100

    Remove print and extra coordinate

diff --git a/esmvalcore/preprocessor/_time.py b/esmvalcore/preprocessor/_time.py
index 612bfa47a..1e29395e3 100644
--- a/esmvalcore/preprocessor/_time.py
+++ b/esmvalcore/preprocessor/_time.py
@@ -411,7 +411,6 @@ def climate_statistics(cube, operator='mean', period='full'):
     operator = get_iris_analysis_operation(operator)
     clim_cube = cube.aggregated_by(clim_coord, operator)
     clim_cube.remove_coord('time')
-    print(clim_cube)
     if clim_cube.coord(clim_coord.name()).is_monotonic():
         iris.util.promote_aux_coord_to_dim_coord(clim_cube, clim_coord.name())
     else:
@@ -474,6 +473,7 @@ def anomalies(cube, period, reference):
         data[indexes] = data[indexes] - ref[cube_coord.points[i]]
 
     cube = cube.copy(data)
+    cube.remove_coord(cube_coord)
     return cube
 
```

Recipe: 
```
# ESMValTool
# recipe_anom_bug.yml
---
documentation:
  description: |
    Recipe for demonstrating a bug. To get wrong results run `git checkout ' master@{2020-03-04}'` in ESMValCore dir. To get good results run `git checkout 'master@{2020-03-03}'` in ESMValCore dir. Use branch `C3S_511_MPQB` from ESMValTool.


  authors:
    - crezee_bas

################################################
# Define some default parameters using anchors #
################################################

commongrid: &commongrid
  regrid:
    target_grid: 0.25x0.25
    scheme: nearest
  regrid_time:  # this is needed for a fully homogeneous time coordinate
    frequency: mon

icefreeland: &icefreeland
  mask_landsea:
    mask_out: sea
  mask_glaciated:
    mask_out: glaciated

commonmask: &commonmask  # should be preceded by commongrid
  mask_fillvalues:
    threshold_fraction: 0.0     # keep all missing values
    min_value: -1e20            # small enough not to alter the data

nonnegative: &nonnegative
  clip:
    minimum: 0.0


################################################
################################################
################################################

datasets_from_1992_2019: &datasets_from_1992_2019
  additional_datasets:
    - {dataset: CDS-SATELLITE-SOIL-MOISTURE, type: sat, project: OBS, mip: Lmon,
       version: CUSTOM-TCDR-ICDR-20200602, tier: 3, start_year: 2015, end_year: 2018}

#     - {dataset: CDS-SATELLITE-SOIL-MOISTURE, project: OBS, tier: 3, type: sat,
#        version: CUSTOM-TCDR-ICDR-20200602, start_year: 1992, end_year: 2019, mip: Lmon}
#     - {dataset: cds-era5-land-monthly, type: reanaly, project: OBS, mip: Lmon,
#        version: 1, tier: 3, start_year: 1992, end_year: 2019}
#     - {dataset: cds-era5-monthly, type: reanaly, project: OBS, mip: Lmon,
#        version: 1, tier: 3, start_year: 1992, end_year: 2019}
#     - {dataset: MERRA2, type: reanaly, project: OBS6, mip: Lmon,
#        version: 5.12.4, tier: 3, start_year: 1992, end_year: 2019}

preprocessors:
  pp_lineplots_ano:
    custom_order: true
    <<: *icefreeland
    <<: *commongrid
    <<: *commonmask
    <<: *nonnegative
    anomalies:
      period: monthly
      reference: [2015,2018]
      standardize: false
    area_statistics:
      operator: mean

diagnostics:
  lineplots_ano:
    variables:
      sm:
        preprocessor: pp_lineplots_ano
        mip: Lmon
    scripts:
      lineplot:
        script: mpqb/mpqb_lineplot.py
    <<: *datasets_from_1992_2019

```
