### ISSUE TITLE
Preprocessor order: positioning of extract_time

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#762]
I have a question about the preprocessor ordering:

Why are the preprocessors `extract_time`, `extract_season` and `extract_month` placed before `cmor_check_data`?

```python
...
    'cmor_check_metadata',
    # Time extraction
    'extract_time',
    'extract_season',
    'extract_month',
    # Data reformatting/CMORization
    'fix_data',
    'cmor_check_data',
    # Level extraction
    'extract_levels',
...
```

That way, they cannot be shuffled around by `custom_order = true`, since they belong to the initial steps:

https://github.com/ESMValGroup/ESMValCore/blob/594cb65498f92e6c08586e86d05933538be09de1/esmvalcore/preprocessor/__init__.py#L133

I guess the reason for this is that `fix_data` is executed after the data is reduced by those 3 preprocessors, but with that reasoning we could also move `fix_data` after `extract_levels`, `extract_region`, etc.

Would it be possible to move those 3 preprocessors further down the preprocessor pipeline (after `cmor_check_data`)? In my case, I want to use `extract_time` after `anomalies`, which is currently not possible.

**Comment by bouweandela** [comment]
I would be fine with changing the order as proposed, since most data is lazy anyway the increase in processing time will probably be small in most cases. @mattiarighi Any opinion?

**Comment by schlunma** [comment]
I found an issue that appears when moving `extract_time` down in the preprocessor ordering:

Right now, the preprocessor `extract_time` is used to extract user-desired time range as given in the recipe by the `start_year` and `end_year` attributes:

https://github.com/ESMValGroup/ESMValCore/blob/505db58d5555cbaf6472e0131fc29066b032885a/esmvalcore/_recipe.py#L307-L316

This is problematic in cases when `custom_order: true` is used and `extract_time` is **not** explicitly specified, e.g.

```yaml
preprocessors:
  test:
    custom_order: true
    area_statistics:
      operator: mean
    climate_statistics:
      operator: mean
      period: full

datasets:
  - {project: CMIP6, ..., start_year: 1900, end_year: 1910}
```

Since `extract_time` is not mentioned in the preprocessor `test`, it is skipped:

https://github.com/ESMValGroup/ESMValCore/blob/505db58d5555cbaf6472e0131fc29066b032885a/esmvalcore/_recipe.py#L800-L806

Note that `extract_time` is neither in `profile`, `INITIAL_STEPS` nor `FINAL_STEPS`.

Thus, the data does not range from the years 1900 to 1910 (as expected), but is given by the individual model file itself. For example, if the model provides one large dataset spanning the years 1850 to 2014, then this whole time series is used.

I propose that we add an additional preprocessor `extract_years` (or a similar name) that simply is a wrapper for `extract_time` and put this into `INITIAL_STEPS` so that it is guaranteed that the user-defined time ranges are extracted. Similar to `load()` or `concatenate()`, `extract_years` should not be mentioned in [this](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html) part of the documentation, but rather be invisible to the regular user.

**Comment by valeriupredoi** [comment]
@schlunma I reckon there's no need for an extra preprocessor, all you have to do is update the settings in `_recipe.py` in `def _get_preprocessor_products()` - note that `_get_default_settings` already sets up time extraction as default, if you call it again via an update function in `_get_preprocessor_products` it should be fine and will run again whenever you have it in the recipe explicitly stated as a preproc step :beer:

**Comment by bouweandela** [comment]
How about simply adding `extract_time` at the start of `order` if it is not in there yet? That would solve the issue without major changes.

Is this issue still up to date? At the ;ast monthly meeting you described a different problem, if I remember correctly?

**Comment by schlunma** [comment]
> How about simply adding `extract_time` at the start of `order` if it is not in there yet? That would solve the issue without major changes.

That works if the user does not explicitly specify `extract_time` in the recipe. However, if the user does (e.g. because the user wants to extract a specific month), then it does not work, because we cannot run a preprocessor with two different settings in our preprocessor pipeline (the settings are stored in a `dict`).

Please note that I have a use case where the order of the preprocessor matters, i.e. doing the extraction of the month at the same time as the years right at the start of the preprocessor chain does **not** give the same results. I also think that adding a preprocessor `extract_years` would not result in major changes.

> Is this issue still up to date? At the last monthly meeting you described a different problem, if I remember correctly?

Yes, it is still up to date, I just didn't have the time to test this thoroughly. I wanted to describe this issue at the meeting, but apparently I failed miserably :smile:

**Comment by bouweandela** [comment]
>> How about simply adding extract_time at the start of order if it is not in there yet? That would solve the issue without major changes.

> That works if the user does not explicitly specify extract_time in the recipe. However, if the user does (e.g. because the user wants to extract a specific month), then it does not work, because we cannot run a preprocessor with two different settings in our preprocessor pipeline (the settings are stored in a dict).

If you specify the arguments of extract_time in the preprocessor section of the recipe, these will overwrite the default (i.e. the years from the dataset).

> Please note that I have a use case where the order of the preprocessor matters, i.e. doing the extraction of the month at the same time as the years right at the start of the preprocessor chain does not give the same results. I also think that adding a preprocessor `extract_years` would not result in major changes.

I'm still not sure I understand what you need. From this text it looks like you would actually like to use the `extract_time` preprocessor function twice in the same preprocessor profile, with the `anomalies` prepreocessor function in between, is that right? Could you give an example of the preprocessor steps as you would like to use them in the recipe?

**Comment by schlunma** [comment]
> I'm still not sure I understand what you need. From this text it looks like you would actually like to use the `extract_time` preprocessor function twice in the same preprocessor profile, with the `anomalies` prepreocessor function in between, is that right? Could you give an example of the preprocessor steps as you would like to use them in the recipe?

Exactly, sorry for not explaining this too well. I want to have a preprocessor that extracts the temperature anomaly for the years 2080 to 2100 relative to the base period 1900-1930. I tried the following preprocessor:

```yaml
preprocessors:
  anomaly:
    custom_order: true
    anomalies:
      period: full
      reference:
        start_year: 1900
        start_month: 1
        start_day: 1
        end_year: 1930
        end_month: 12
        end_day: 31
    extract_time:
      start_year: 2080
      start_month: 1
      start_day: 1
      end_year: 2100
      end_month: 12
      end_day: 31
```

on datasets like this:

```yaml
- {dataset: ..., start_year: 1900, end_year: 2100, exp: [historical, ssp585], ...}
```

I encountered the following problems:

- `master` branch: not possible because `extract_time` cannot be shuffled around via `custom_order: true`. As a consequence I get the anomaly for the full range 1900-2100.
- Simply moving `extract_time` down in the preprocessor order: The time extraction of the years 1900 to 2100 as specified in the recipe does not happen anymore, so the actual time range given to the preprocessor depends on the different datasets and how they group their files.

Thus, for this use case it would be beneficial to run the `extract_time` preprocessor twice. This can be achieved by adding an additional preprocessor step `extract_years` that is added to the `INITIAL_STEPS`.

**Comment by bouweandela** [comment]
So what you would actually like to do is:
```
preprocessors:
  anomaly:
    custom_order: true
    extract_time:
      start_year: 1900
      end_year: 2100
    anomalies:
      period: full
      reference:
        start_year: 1900
        start_month: 1
        start_day: 1
        end_year: 1930
        end_month: 12
        end_day: 31
    extract_time:
      start_year: 2080
      start_month: 1
      start_day: 1
      end_year: 2100
      end_month: 12
      end_day: 31
```
right?

Do you think that having the option to do this makes sense for other preprocessor functions than `anomalies` too? Because if not, it might make more sense to just add a `target_period` keyword argument or something similar to the anomalies preprocessor function where you specify the desired target period.

**Comment by schlunma** [comment]
Yes, only that the first call to `extract_time` should be handled automatically by the time period I specified in the recipe as `start_year` and `end_year`.

I do not use this, but I think this might for example also be useful for the `detrend` preprocessor. For me a key feature of our preprocessor is that I can move the different functions around as I like, and I think that the current implantation is not very flexible in terms of temporal extraction.

**Comment by bascrezee** [comment]
I ran into this issue as well. For me the big surprise was to find out that `custom_order: true` is basically not true ! I would have really expected the preprocessor order to be exactly the way I specify it. My use case was: 

```
# Let's have a look at the standardized anomalies for soil moisture (with all available input years as reference) of the drought in Europe in 2003
  anomaly:
    custom_order: true
    anomalies:
      period: monthly
      standardize: true
extract_time:
      start_year: 2003
      start_month: 7
      start_day: 1
      end_year: 2003
      end_month: 9
      end_day: 1
```

The result is a completely masked field. Indeed because `extract_time` takes place before `anomalies`. Didn't expect that.
