### ISSUE TITLE
Adding preprocessor "difference"

### ISSUE THREAD

**Issue by ruthlorenz** [ESMValGroup/ESMValCore#833]
**Is your feature request related to a problem? Please describe.**
For some recipes it would be convenient if one could calculate the difference between two preprocessors as an additional preprocessor. For instance the difference between two time periods or a spatial anomaly (as in some preprocessed lat,lon field minus the global mean), see needed e.g. here https://github.com/ESMValGroup/ESMValTool/issues/1850
This can be done in the diagnostic but in the example above it would be more elegant to do it directly as a preprocessor.

If there are other use cases where this is needed and if this is reasonably simple to implement I think this would be a nice feature.

**Would you be able to help out?**
Maybe, would definitely need some guidance on the best way to implement this and help with the tests.

**Comment by Peter9192** [comment]
I've been thinking about this one. I really see the use case and like the idea, but I'm not sure if it plays well with the current setup of the preprocessor. You would need a preprocessor that takes the output of previous preprocessors. I don't think that's currently possible.

What we *could* do is make a diagnostic that does this, and then use its output as ancestor for the remaining diagnostics. Something like:

```yaml
diagnostics:
  tas_difference:
    variables:
      tas_global_future:
        short_name: tas
        preprocessor: future
      tas_global_reference:
        short_name: tas
        preprocessor: reference
    scripts:
      difference:
        script: utils/difference.py
  tas_map:
    ancestors: [tas_difference/difference]
    script: plot_map.py
```

This use case is also interesting for #498 . In the mockup notebook there, something like this should be much easier.
