### ISSUE TITLE
thetao CESM2 z-level ("olevel") needs fix to convert units from cm to m

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#859]
CESM2 (eg `/badc/cmip6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/Omon/thetao/gn/latest/thetao_Omon_CESM2_historical_r1i1p1f1_gn_185001-201412.nc` on Jasmin) has depth (generic vertical level, `olevel`) units in `centimeters` (and its bounds in meters!) but the cmor checks in the preprocessor are not picking this up). Run test:
```yaml
---
documentation:
  description: |
    Test

  authors:
    - righi_mattia

diagnostics:
  BerkeleyEarth:
    description: BerkeleyEarth check
    variables:
      thetao:
    additional_datasets:
#/badc/cmip6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/Omon/thetao/gn/latest/thetao_Omon_CESM2_historical_r1i1p1f1_gn_185001-201412.nc
      - {dataset: CESM2, project: CMIP6, exp: historical, mip: Omon, ensemble: r1i1p1f1, grid: gn, start_year: 1990, end_year: 1995}
    scripts: null
```
I have forgotten - are we expecting checks on `olevel` or this is something we should fix via a fix file? seems a bit odd since it's  a valid dimensional coordinate and not even `--check_level strict` picks up the weird units and wonky bounds :beer:
