### ISSUE TITLE
Generic level checks lead to inconsistent ESMValTool runs

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#883]
See ESMValGroup/ESMValCore#598:

I still have this weird issue that (I think) depends on the order of which the datasets are read:

The following recipe sometimes works, sometimes fails with 

```
esmvalcore.cmor.check.CMORCheckError: There were errors in variable cl:
lev: units should be 1, not m
 lev: has values > valid_max = 1.0
```

for `HadGEM3-GC31-MM` and sometimes with the same error for `ACCESS-ESM1-5`.

Each of these datasets does **NOT** throw an error when used alone.

What is going on here?

This recipe sometimes works, sometimes not:

```yaml
# ESMValTool
---
documentation:
  authors:
    - schlund_manuel

  maintainer:
    - schlund_manuel

  references:
    - gregory04grl

  projects:
    - crescendo


diagnostics:

  diag_test:
    variables:
      cl:
        project: CMIP6
        exp: historical
        mip: Amon
        start_year: 2004
        end_year: 2004
    additional_datasets:
      - {dataset: ACCESS-ESM1-5,   ensemble: r1i1p1f1, grid: gn}
      - {dataset: GISS-E2-1-G,     ensemble: r1i1p1f1, grid: gn}
      - {dataset: GISS-E2-1-H,     ensemble: r1i1p1f1, grid: gn}
      - {dataset: HadGEM3-GC31-LL, ensemble: r1i1p1f3, grid: gn}
      - {dataset: HadGEM3-GC31-MM, ensemble: r1i1p1f3, grid: gn}
    scripts:
      null
```

This recipe always works:

```yaml
# ESMValTool
---
documentation:
  authors:
    - schlund_manuel

  maintainer:
    - schlund_manuel

  references:
    - gregory04grl

  projects:
    - crescendo


diagnostics:

  diag_test:
    variables:
      cl:
        project: CMIP6
        exp: historical
        mip: Amon
        start_year: 2004
        end_year: 2004
    additional_datasets:
      - {dataset: ACCESS-ESM1-5,   ensemble: r1i1p1f1, grid: gn}
    scripts:
      null
```
