### ISSUE TITLE
Remove option to specify additional_datasets at diagnostic level

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#92]
At the moment, datasets can be specified at three levels:
1) `datasets` section
2) `additional_datasets` section in diagnostic section
3) `additional_datasets` section in variable section

I think that the second option is not needed, so it would make the recipe format easier to understand if we remove this possibility.

**Comment by schlunma** [comment]
I agree that the recipe format would be easier to understand with this change, but I don't think removing option 2 is a good idea:

Consider a long recipe with lots of different diagnostics so that it's not possible to use option 1. Sometimes it is necessary to use several models for different variables where each variable has its individual `OBS` dataset. In this case, the only convenient way to implement this (without repeating the same models over and over) is to put the models into option 2 and the `OBS` datasets into option 3.

In my opinion, we could remove option 1 (an maybe rename the `additional_datasets` key in the diagnostic section to just `datasets`). If there's the need to use the same datasets for multiple diagnostics, this could be solved with yaml anchors.

A lot of this would be easier if `yaml` supported a syntax like this:

```yaml
anchor: &datasets
  - a
  - b

# works
diagnostic
  additional_datasets: *datasets

# does NOT work
diagnostic:
  additional_datasets:
    <<: *datasets
    - c
```
Unfortunately, this seconds option is not possible (right now).
