### ISSUE TITLE
Concatenation of ocean 3D data (from two experiments) doesn't work if aux_coords differ

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#932]
@koldunovn brought this up in a long-forgotten but alas still open #753 and I have just found this thanks to @npgillett asking me something offline - in a nutshell: concatenation of cubes at `io.concatenate()` stage gets completely hosed if cubes have `aux_coords` that differ (could be name, metadata, or actual data of one or more aux_coords - I have seen all of these manifest themselves), this is happening mostly for two different experiments that need to be used for data complementary (ie: historical from 1850 to 2014 and ssp45: from 2015 to the end of world due to Greta devouring it). Options we have to fix this bug/add enhancement to concatenation:

- ask @bjlittle and the iris folk to be less strict about `cube.concatenate_cube()`
- fix the aux_coords before concatenation - but this is tricky, which one of them would be the reference by which the other gets fixed?
- remove the aux_coords and re-add them to the resulting concatenated cube (that will concatenate this time around), but here, again, which one to be used as correct/reference?

Brainstorming ahoy! Also, if this has been resolved elsewhere I will buy a pint, but am sure it hasn't :beer:

**Comment by valeriupredoi** [comment]
also, here's an example recipe that @npgillett had issues with, perfectly showing the issue with the aux coords data differing:
```yaml
---
documentation:
  description: |
    Produces figures from Gillett et al. (2020)
    'Constraining human contributions to observed warming since preindustrial'
  authors:
    - predoi_valeriu
  references:
    - gillett20ncc
preprocessors:
  regrid_5_5:
    regrid:
      target_grid: 5x5
      scheme: linear
diagnostics:
  gillett20_figs:
    description: Preprocess data needed for Gillett et al. (2020) figures.
    variables:
      siconc:
        preprocessor: regrid_5_5
        reference_dataset: HadCRUT4
        field: T2Ms
        mip: SImon
        project: CMIP6
        start_year: 1850
        end_year: 2019
        additional_datasets:
          - {dataset: FGOALS-g3, ensemble: r1i1p1f1, grid: gn, exp: [historical,ssp245] }
    scripts:
      fig1:
        script: examples/correlate.py
```
