### ISSUE TITLE
Derivation even if missing data

### ISSUE THREAD

**Issue by remi-kazeroni** [ESMValGroup/ESMValCore#988]
**Describe the bug**
When running the `recipe_preprocessor_derive_test.yml` using the `skip_nonexistent` option, the ESMValCore tries to do the derivation on 0-len cube that correspond to missing files and this results in an error:
`ERROR   esmvalcore.preprocessor:274 Failed to run concatenate([], {})
`

On Mistral, the mising data being:
```
      ctotal:
        <<: *alb_cmip5
        mip: Lmon
        additional_datasets:
          - {dataset: CanESM2, ensemble: r1i1p1}
```

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory
[recipe_preprocessor_derive_test.yml.txt](https://github.com/ESMValGroup/ESMValCore/files/5943473/recipe_preprocessor_derive_test.yml.txt)
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/5943472/main_log_debug.txt)
